/** Catálogo central de permissões (Fase 1K-D.2). Fonte única backend + frontend. */

export type PermissionType = "menu" | "section" | "tab" | "action";
export type PermissionRisk = "normal" | "sensitive" | "critical";

export type PermissionCatalogEntry = {
  key: string;
  label: string;
  group: string;
  module: string;
  description: string;
  type: PermissionType;
  parentKey?: string;
  risk?: PermissionRisk;
  requires?: string[];
  recommendedFor?: string[];
};

type PermInput = Omit<PermissionCatalogEntry, "risk"> & { risk?: PermissionRisk };

function perm(entry: PermInput): PermissionCatalogEntry {
  return {
    risk: "normal",
    ...entry,
  };
}

const G = "Geral";
const CRM = "CRM";
const CLI = "Clientes";
const PROP = "Propostas";
const SO = "Pedidos de Venda";
const ENG = "Engenharia / Produtos";
const COMP = "Compras";
const PRC = "Precificação / Impostos";
const OPS = "Custos / Operação";
const SYS = "Configurações / Sistema";
const MNT = "Manutenção";
const FLT = "Gestão de Frota";

const FIN = "Financeiro";

export const PERMISSION_CATALOG: PermissionCatalogEntry[] = [
  // —— Geral ——
  perm({ key: "dashboard.view", label: "Dashboard", group: G, module: "dashboard", description: "Visualizar painel principal.", type: "menu" }),
  perm({ key: "reports.view", label: "Relatórios", group: G, module: "reports", description: "Acessar relatórios e BI.", type: "menu" }),
  perm({ key: "guide.view", label: "Guia do Sistema", group: G, module: "guide", description: "Acessar o guia funcional do sistema.", type: "menu" }),

  // —— Financeiro ——
  perm({
    key: "finance.view",
    label: "Financeiro",
    group: FIN,
    module: "finance",
    description: "Acessar o domínio Financeiro no menu principal.",
    type: "menu",
  }),
  perm({
    key: "finance.accountsReceivable.view",
    label: "Financeiro — Contas a Receber",
    group: FIN,
    module: "finance",
    description: "Consultar dashboard read-only de Contas a Receber (Nomus sync local).",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.accountsReceivable.export",
    label: "Financeiro — Exportar Contas a Receber",
    group: FIN,
    module: "finance",
    description: "Exportar CSV da carteira de Contas a Receber com filtros aplicados.",
    type: "action",
    parentKey: "finance.accountsReceivable.view",
    requires: ["finance.view", "finance.accountsReceivable.view"],
  }),

  // —— CRM ——
  perm({ key: "crm.view", label: "CRM Comercial", group: CRM, module: "crm-commercial", description: "Acessar o módulo CRM Comercial.", type: "menu" }),
  perm({
    key: "crm.general.view",
    label: "CRM — Gestão Geral",
    group: CRM,
    module: "crm-commercial",
    description: "Aba de gestão comercial geral.",
    type: "tab",
    parentKey: "crm.view",
    requires: ["crm.view"],
  }),
  perm({
    key: "crm.seller.view",
    label: "CRM — Gestão por Vendedor",
    group: CRM,
    module: "crm-commercial",
    description: "Aba de gestão por vendedor.",
    type: "tab",
    parentKey: "crm.view",
    requires: ["crm.view"],
  }),
  perm({
    key: "crm.seller.all",
    label: "CRM — Ver todos os vendedores",
    group: CRM,
    module: "crm-commercial",
    description: "Ver dados de todos os vendedores.",
    type: "action",
    parentKey: "crm.seller.view",
    requires: ["crm.view", "crm.seller.view"],
    risk: "sensitive",
  }),
  perm({
    key: "crm.seller.own",
    label: "CRM — Ver somente próprio vendedor",
    group: CRM,
    module: "crm-commercial",
    description: "Ver apenas dados do vendedor vinculado.",
    type: "action",
    parentKey: "crm.seller.view",
    requires: ["crm.view", "crm.seller.view"],
  }),
  perm({
    key: "crm.customer_cockpit.view",
    label: "CRM — Cockpit do Cliente",
    group: CRM,
    module: "crm-commercial",
    description: "Carteira e cockpit do cliente no CRM.",
    type: "section",
    parentKey: "crm.view",
    requires: ["crm.view"],
  }),
  perm({
    key: "crm.activities.create",
    label: "CRM — Criar atividade/contato",
    group: CRM,
    module: "crm-commercial",
    description: "Registrar atividades e contatos.",
    type: "action",
    parentKey: "crm.customer_cockpit.view",
    requires: ["crm.view", "crm.customer_cockpit.view"],
  }),
  perm({
    key: "crm.activities.edit",
    label: "CRM — Editar/concluir atividade",
    group: CRM,
    module: "crm-commercial",
    description: "Editar ou concluir atividades.",
    type: "action",
    parentKey: "crm.customer_cockpit.view",
    requires: ["crm.view", "crm.customer_cockpit.view"],
  }),
  perm({
    key: "crm.profile.edit",
    label: "CRM — Editar perfil comercial do cliente",
    group: CRM,
    module: "crm-commercial",
    description: "Editar perfil de relacionamento comercial.",
    type: "action",
    parentKey: "crm.customer_cockpit.view",
    requires: ["crm.view", "crm.customer_cockpit.view"],
  }),

  // —— Clientes ——
  perm({ key: "customers.view", label: "Clientes", group: CLI, module: "customers", description: "Consultar clientes.", type: "menu" }),
  perm({
    key: "customers.create",
    label: "Clientes — Criar",
    group: CLI,
    module: "customers",
    description: "Cadastrar novos clientes.",
    type: "action",
    parentKey: "customers.view",
    requires: ["customers.view"],
  }),
  perm({
    key: "customers.edit",
    label: "Clientes — Editar",
    group: CLI,
    module: "customers",
    description: "Editar cadastro de clientes.",
    type: "action",
    parentKey: "customers.view",
    requires: ["customers.view"],
  }),
  perm({
    key: "customers.commercial360.view",
    label: "Clientes — Visão Comercial 360",
    group: CLI,
    module: "customers",
    description: "Visão comercial ampliada do cliente.",
    type: "section",
    parentKey: "customers.view",
    requires: ["customers.view"],
  }),

  // —— Propostas ——
  perm({ key: "proposals.view", label: "Propostas", group: PROP, module: "proposals", description: "Consultar propostas.", type: "menu" }),
  perm({
    key: "proposals.create",
    label: "Propostas — Criar",
    group: PROP,
    module: "proposals",
    description: "Criar novas propostas.",
    type: "action",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),
  perm({
    key: "proposals.edit",
    label: "Propostas — Editar",
    group: PROP,
    module: "proposals",
    description: "Editar propostas existentes.",
    type: "action",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),
  perm({
    key: "proposals.delete",
    label: "Propostas — Excluir",
    group: PROP,
    module: "proposals",
    description: "Excluir propostas.",
    type: "action",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
    risk: "critical",
  }),
  perm({
    key: "proposals.print",
    label: "Propostas — Imprimir/gerar cliente",
    group: PROP,
    module: "proposals",
    description: "Imprimir ou gerar versão para o cliente.",
    type: "action",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),
  perm({
    key: "proposals.indicators.view",
    label: "Propostas — Indicadores",
    group: PROP,
    module: "proposals",
    description: "Indicadores e análises de propostas.",
    type: "tab",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),
  perm({
    key: "proposals.material_report.view",
    label: "Propostas — Relatório Geral de MP",
    group: PROP,
    module: "proposals",
    description: "Relatório consolidado de matéria-prima.",
    type: "section",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),

  // —— Pedidos ——
  perm({ key: "sales_orders.view", label: "Pedidos de venda", group: SO, module: "sales-orders", description: "Consultar pedidos de venda.", type: "menu" }),
  perm({
    key: "sales_orders.detail.view",
    label: "Pedidos — Detalhe",
    group: SO,
    module: "sales-orders",
    description: "Visualizar detalhes do pedido.",
    type: "section",
    parentKey: "sales_orders.view",
    requires: ["sales_orders.view"],
  }),
  perm({
    key: "sales_orders.invoice.view",
    label: "Pedidos — Faturamento/NFe",
    group: SO,
    module: "sales-orders",
    description: "Informações de faturamento e NFe.",
    type: "section",
    parentKey: "sales_orders.view",
    requires: ["sales_orders.view"],
  }),

  // —— Engenharia / Produtos ——
  perm({ key: "products.view", label: "Engenharia / Produtos", group: ENG, module: "products", description: "Consultar produtos e engenharia.", type: "menu" }),
  perm({
    key: "products.create",
    label: "Engenharia — Criar item",
    group: ENG,
    module: "products",
    description: "Criar produtos ou componentes.",
    type: "action",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.edit",
    label: "Engenharia — Editar item",
    group: ENG,
    module: "products",
    description: "Editar produtos ou componentes.",
    type: "action",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.delete",
    label: "Engenharia — Excluir item",
    group: ENG,
    module: "products",
    description: "Excluir itens de engenharia.",
    type: "action",
    parentKey: "products.view",
    requires: ["products.view"],
    risk: "critical",
  }),
  perm({
    key: "products.export.engineering",
    label: "Engenharia — Exportar layout",
    group: ENG,
    module: "products",
    description: "Exportar planilha de engenharia.",
    type: "action",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.info",
    label: "Engenharia — Aba Informações",
    group: ENG,
    module: "products",
    description: "Aba de identificação do produto.",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.bom",
    label: "Engenharia — Aba Estrutura BOM",
    group: ENG,
    module: "products",
    description: "Aba de estrutura (BOM).",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.routing",
    label: "Engenharia — Aba Processo/Roteiro",
    group: ENG,
    module: "products",
    description: "Aba de roteiro de processo.",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.tree",
    label: "Engenharia — Aba Estrutura em Árvore",
    group: ENG,
    module: "products",
    description: "Aba de estrutura em árvore.",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.cost",
    label: "Engenharia — Aba Análise de Custo",
    group: ENG,
    module: "products",
    description: "Aba de análise de custo.",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
    risk: "sensitive",
  }),
  perm({
    key: "products.tab.composition",
    label: "Engenharia — Aba Composição de Custos",
    group: ENG,
    module: "products",
    description: "Aba de composição de custos (open book).",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
    risk: "sensitive",
  }),

  // —— Compras ——
  perm({ key: "purchases.view", label: "Compras", group: COMP, module: "purchases", description: "Consultar solicitações de compra.", type: "menu" }),
  perm({
    key: "purchases.create",
    label: "Compras — Criar solicitação",
    group: COMP,
    module: "purchases",
    description: "Criar solicitações de compra.",
    type: "action",
    parentKey: "purchases.view",
    requires: ["purchases.view"],
  }),
  perm({
    key: "purchases.edit",
    label: "Compras — Editar solicitação",
    group: COMP,
    module: "purchases",
    description: "Editar solicitações de compra.",
    type: "action",
    parentKey: "purchases.view",
    requires: ["purchases.view"],
  }),
  perm({
    key: "purchases.delete",
    label: "Compras — Excluir/cancelar",
    group: COMP,
    module: "purchases",
    description: "Cancelar ou excluir solicitações.",
    type: "action",
    parentKey: "purchases.view",
    requires: ["purchases.view"],
    risk: "critical",
  }),
  perm({
    key: "purchases.indicators.view",
    label: "Compras — Indicadores",
    group: COMP,
    module: "purchases",
    description: "Indicadores do módulo de compras.",
    type: "section",
    parentKey: "purchases.view",
    requires: ["purchases.view"],
  }),

  // —— Precificação / Impostos ——
  perm({ key: "pricing.view", label: "Formação de Preço", group: PRC, module: "pricing", description: "Acessar formação de preço.", type: "menu" }),
  perm({
    key: "pricing.simulate",
    label: "Precificação — Simular preço",
    group: PRC,
    module: "pricing",
    description: "Simular preços unitários ou em lote.",
    type: "action",
    parentKey: "pricing.view",
    requires: ["pricing.view"],
  }),
  perm({
    key: "pricing.generate_tables",
    label: "Precificação — Gerar tabelas comerciais",
    group: PRC,
    module: "pricing",
    description: "Gerar versões DRAFT de tabelas comerciais.",
    type: "action",
    parentKey: "pricing.view",
    requires: ["pricing.view"],
    risk: "sensitive",
  }),
  perm({
    key: "pricing.publish_tables",
    label: "Precificação — Publicar tabelas",
    group: PRC,
    module: "pricing",
    description: "Publicar versões de tabelas comerciais.",
    type: "action",
    parentKey: "pricing.view",
    requires: ["pricing.view"],
    risk: "critical",
  }),
  perm({ key: "taxes.view", label: "Regras fiscais", group: PRC, module: "taxes", description: "Consultar regras fiscais.", type: "menu" }),
  perm({
    key: "taxes.edit",
    label: "Regras fiscais — Editar",
    group: PRC,
    module: "taxes",
    description: "Editar regras fiscais.",
    type: "action",
    parentKey: "taxes.view",
    requires: ["taxes.view"],
    risk: "sensitive",
  }),

  // —— Custos / Operação ——
  perm({ key: "employees.view", label: "Pessoas / RH", group: OPS, module: "employees", description: "Consultar colaboradores (módulo administrativo de RH).", type: "menu" }),
  perm({
    key: "employees.edit",
    label: "Pessoas / RH — Editar",
    group: OPS,
    module: "employees",
    description: "Editar colaboradores no módulo administrativo de RH.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "sensitive",
  }),
  perm({ key: "machines.view", label: "Máquinas", group: OPS, module: "machines", description: "Consultar máquinas.", type: "menu" }),
  perm({
    key: "machines.edit",
    label: "Máquinas — Editar",
    group: OPS,
    module: "machines",
    description: "Editar máquinas e centros de trabalho.",
    type: "action",
    parentKey: "machines.view",
    requires: ["machines.view"],
  }),
  perm({ key: "materials.view", label: "Materiais", group: OPS, module: "materials", description: "Consultar materiais.", type: "menu" }),
  perm({
    key: "materials.edit",
    label: "Materiais — Editar",
    group: OPS,
    module: "materials",
    description: "Editar materiais e suprimentos.",
    type: "action",
    parentKey: "materials.view",
    requires: ["materials.view"],
  }),
  perm({ key: "opex.view", label: "Custos indiretos / OPEX", group: OPS, module: "opex", description: "Consultar custos indiretos.", type: "menu" }),
  perm({
    key: "opex.edit",
    label: "OPEX — Editar",
    group: OPS,
    module: "opex",
    description: "Editar custos indiretos.",
    type: "action",
    parentKey: "opex.view",
    requires: ["opex.view"],
    risk: "sensitive",
  }),
  perm({ key: "simulations.view", label: "Simulações", group: OPS, module: "simulations", description: "Consultar simulações.", type: "menu" }),
  perm({
    key: "simulations.create",
    label: "Simulações — Criar",
    group: OPS,
    module: "simulations",
    description: "Criar cenários de simulação.",
    type: "action",
    parentKey: "simulations.view",
    requires: ["simulations.view"],
  }),
  /** Legado: pacote único de custos (compatibilidade 1K-D). */
  perm({
    key: "costs.view",
    label: "Custos — visualizar (legado)",
    group: OPS,
    module: "costs",
    description: "Permissão legada que libera módulos de custo/operação. Prefira permissões específicas por módulo.",
    type: "menu",
    risk: "sensitive",
  }),

  // —— Configurações ——
  perm({ key: "settings.view", label: "Configurações", group: SYS, module: "settings", description: "Acessar configurações do sistema.", type: "menu" }),
  perm({
    key: "users.manage",
    label: "Usuários e Permissões",
    group: SYS,
    module: "settings",
    description: "Cadastrar e administrar usuários.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
    risk: "critical",
  }),
  perm({
    key: "settings.branding.view",
    label: "Configurações — Marca/identidade",
    group: SYS,
    module: "settings",
    description: "Visualizar identidade visual.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
  }),
  perm({
    key: "settings.branding.edit",
    label: "Configurações — Editar marca/identidade",
    group: SYS,
    module: "settings",
    description: "Editar logos e identidade.",
    type: "action",
    parentKey: "settings.branding.view",
    requires: ["settings.view", "settings.branding.view"],
  }),
  perm({
    key: "settings.global_params.view",
    label: "Configurações — Parâmetros globais",
    group: SYS,
    module: "settings",
    description: "Visualizar parâmetros globais.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
    risk: "sensitive",
  }),
  perm({
    key: "settings.global_params.edit",
    label: "Configurações — Editar parâmetros globais",
    group: SYS,
    module: "settings",
    description: "Editar parâmetros globais de cálculo.",
    type: "action",
    parentKey: "settings.global_params.view",
    requires: ["settings.view", "settings.global_params.view"],
    risk: "critical",
  }),
  perm({
    key: "settings.nomus.view",
    label: "Configurações — Integração Nomus",
    group: SYS,
    module: "settings",
    description: "Visualizar logs e integração Nomus.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
    risk: "sensitive",
  }),
  perm({
    key: "settings.nomus.sync",
    label: "Configurações — Executar sincronização Nomus",
    group: SYS,
    module: "settings",
    description: "Disparar sincronização com Nomus.",
    type: "action",
    parentKey: "settings.nomus.view",
    requires: ["settings.view", "settings.nomus.view"],
    risk: "critical",
  }),
  perm({
    key: "settings.price_tables.view",
    label: "Configurações — Tabelas de preço",
    group: SYS,
    module: "settings",
    description: "Visualizar tabelas de preço comerciais.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
  }),
  perm({
    key: "settings.price_tables.manage",
    label: "Configurações — Gerenciar tabelas de preço",
    group: SYS,
    module: "settings",
    description: "Gerenciar versões e itens de tabelas.",
    type: "action",
    parentKey: "settings.price_tables.view",
    requires: ["settings.view", "settings.price_tables.view"],
    risk: "critical",
  }),
  perm({
    key: "settings.operational.view",
    label: "Configurações — Operacional",
    group: SYS,
    module: "settings",
    description: "Visualizar estrutura operacional (cargos, encargos).",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
  }),
  perm({
    key: "settings.operational.manage",
    label: "Configurações — Gerenciar operacional",
    group: SYS,
    module: "settings",
    description: "Editar cargos, encargos e benefícios.",
    type: "action",
    parentKey: "settings.operational.view",
    requires: ["settings.view", "settings.operational.view"],
    risk: "sensitive",
  }),

  // —— Manutenção ——
  perm({ key: "maintenance.view", label: "Manutenção", group: MNT, module: "maintenance", description: "Acessar manutenção predial.", type: "menu" }),
  perm({
    key: "maintenance.manage",
    label: "Manutenção — Gerenciar",
    group: MNT,
    module: "maintenance",
    description: "Gerenciar registros de manutenção.",
    type: "action",
    parentKey: "maintenance.view",
    requires: ["maintenance.view"],
  }),

  // —— Gestão de Frota (legado + granular; legado implica granular no backend) ——
  perm({
    key: "fleet.view",
    label: "Gestão de Frota — Acesso",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada: acesso ao módulo e visualização geral (sem valores financeiros).",
    type: "menu",
  }),
  perm({
    key: "fleet.dashboard.view",
    label: "Frota — Dashboard",
    group: FLT,
    module: "fleet",
    description: "Visualizar painel e indicadores operacionais da frota.",
    type: "section",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.reports.view",
    label: "Frota — Relatórios",
    group: FLT,
    module: "fleet",
    description: "Consultar relatórios operacionais da frota.",
    type: "section",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.vehicles.view",
    label: "Frota — Ver veículos",
    group: FLT,
    module: "fleet",
    description: "Listar e consultar fichas de veículos.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.vehicles.create",
    label: "Frota — Cadastrar veículos",
    group: FLT,
    module: "fleet",
    description: "Incluir novos veículos na frota.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view", "fleet.vehicles.view"],
  }),
  perm({
    key: "fleet.vehicles.edit",
    label: "Frota — Editar veículos",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada: cadastrar, editar veículos, contratos e documentos vinculados.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view", "fleet.vehicles.view"],
  }),
  perm({
    key: "fleet.vehicles.status.manage",
    label: "Frota — Status do veículo",
    group: FLT,
    module: "fleet",
    description: "Alterar status operacional, bloqueio e baixa de veículos.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view", "fleet.vehicles.view"],
    risk: "sensitive",
  }),
  perm({
    key: "fleet.contracts.view",
    label: "Frota — Ver contratos",
    group: FLT,
    module: "fleet",
    description: "Consultar contratos de locação e vínculos.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.contracts.manage",
    label: "Frota — Gerenciar contratos",
    group: FLT,
    module: "fleet",
    description: "Criar e alterar contratos de veículos.",
    type: "action",
    parentKey: "fleet.contracts.view",
    requires: ["fleet.view", "fleet.contracts.view"],
  }),
  perm({
    key: "fleet.documents.view",
    label: "Frota — Ver documentos",
    group: FLT,
    module: "fleet",
    description: "Consultar documentos e vencimentos dos veículos.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.documents.manage",
    label: "Frota — Gerenciar documentos",
    group: FLT,
    module: "fleet",
    description: "Cadastrar e atualizar documentos da frota.",
    type: "action",
    parentKey: "fleet.documents.view",
    requires: ["fleet.view", "fleet.documents.view"],
  }),
  perm({
    key: "fleet.drivers.view",
    label: "Frota — Ver motoristas",
    group: FLT,
    module: "fleet",
    description: "Consultar cadastro de motoristas e CNH.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.drivers.manage",
    label: "Frota — Gerenciar motoristas",
    group: FLT,
    module: "fleet",
    description: "Cadastrar e editar motoristas.",
    type: "action",
    parentKey: "fleet.drivers.view",
    requires: ["fleet.view", "fleet.drivers.view"],
  }),
  perm({
    key: "fleet.reservations.view",
    label: "Frota — Ver reservas",
    group: FLT,
    module: "fleet",
    description: "Consultar agenda e reservas de veículos.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.reservations.create",
    label: "Frota — Criar reservas",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada: criar reservas e operar retirada/devolução (checkout/check-in).",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
  }),
  perm({
    key: "fleet.reservations.approve",
    label: "Frota — Aprovar reservas",
    group: FLT,
    module: "fleet",
    description: "Permissão legada: aprovar ou rejeitar solicitações de reserva.",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
    risk: "critical",
  }),
  perm({
    key: "fleet.reservations.manage",
    label: "Frota — Administrar reservas",
    group: FLT,
    module: "fleet",
    description: "Alterar reservas, substituir veículo e ações administrativas.",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
    risk: "sensitive",
  }),
  perm({
    key: "fleet.usage.checkout",
    label: "Frota — Retirada (checkout)",
    group: FLT,
    module: "fleet",
    description: "Registrar retirada do veículo e checklist de saída.",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
  }),
  perm({
    key: "fleet.usage.checkin",
    label: "Frota — Devolução (check-in)",
    group: FLT,
    module: "fleet",
    description: "Registrar devolução do veículo e checklist de retorno.",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
  }),
  perm({
    key: "fleet.maintenance.view",
    label: "Frota — Ver manutenções",
    group: FLT,
    module: "fleet",
    description: "Consultar ordens e histórico de manutenção.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.maintenance.manage",
    label: "Frota — Gerenciar manutenções",
    group: FLT,
    module: "fleet",
    description: "Permissão legada: abrir, editar e encerrar manutenções.",
    type: "action",
    parentKey: "fleet.maintenance.view",
    requires: ["fleet.view", "fleet.maintenance.view"],
  }),
  perm({
    key: "fleet.costs.view",
    label: "Frota — Ver custos",
    group: FLT,
    module: "fleet",
    description: "Consultar lançamentos de custos (valores podem permanecer mascarados).",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.costs.manage",
    label: "Frota — Lançar custos",
    group: FLT,
    module: "fleet",
    description: "Registrar e alterar custos operacionais da frota.",
    type: "action",
    parentKey: "fleet.costs.view",
    requires: ["fleet.view", "fleet.costs.view"],
    risk: "sensitive",
  }),
  perm({
    key: "fleet.financial.view",
    label: "Frota — Dados financeiros",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada: visualizar valores monetários, multas e indicadores financeiros.",
    type: "action",
    parentKey: "fleet.costs.view",
    requires: ["fleet.view", "fleet.costs.view"],
    risk: "critical",
  }),
  perm({
    key: "fleet.manage",
    label: "Frota — Administrador (legado)",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada ampla: quase todas as operações, exceto configurações (exige fleet.settings.manage).",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
    risk: "critical",
  }),
  perm({
    key: "fleet.settings.manage",
    label: "Frota — Configurações",
    group: FLT,
    module: "fleet",
    description: "Alterar parâmetros, importações e políticas do módulo de frota.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
    risk: "critical",
  }),
];

export const ALL_PERMISSION_KEYS = PERMISSION_CATALOG.map((p) => p.key);

export const PERMISSION_GROUP_ORDER = [
  G,
  CRM,
  CLI,
  PROP,
  SO,
  ENG,
  COMP,
  PRC,
  OPS,
  SYS,
  MNT,
  FLT,
] as const;
