/** Catálogo central de permissões (Fase 1K-D.2). Fonte única backend + frontend. */

export type PermissionType = "menu" | "section" | "tab" | "action";
export type PermissionRisk = "normal" | "sensitive" | "critical";

export type PermissionCatalogEntry = {
  key: string;
  label: string;
  group: string;
  module: string;
  description: string;
  type: PermissionType;
  parentKey?: string;
  risk?: PermissionRisk;
  requires?: string[];
  recommendedFor?: string[];
};

type PermInput = Omit<PermissionCatalogEntry, "risk"> & { risk?: PermissionRisk };

function perm(entry: PermInput): PermissionCatalogEntry {
  return {
    risk: "normal",
    ...entry,
  };
}

const G = "Geral";
const CRM = "CRM";
const CLI = "Clientes";
const PROP = "Propostas";
const SO = "Pedidos de Venda";
const ENG = "Engenharia / Produtos";
const COMP = "Compras";
const PRC = "Precificação / Impostos";
const OPS = "Custos / Operação";
const SYS = "Configurações / Sistema";
const MNT = "Manutenção";
const PRJ = "Projetos";
const FLT = "Gestão de Frota";
const INV = "Estoque";
const CM = "Comissões";

const FIN = "Financeiro";

export const PERMISSION_CATALOG: PermissionCatalogEntry[] = [
  // —— Geral ——
  perm({ key: "dashboard.view", label: "Dashboard", group: G, module: "dashboard", description: "Visualizar painel principal.", type: "menu" }),
  perm({ key: "reports.view", label: "Relatórios", group: G, module: "reports", description: "Acessar relatórios e BI.", type: "menu" }),
  perm({
    key: "reports.material_demand.view",
    label: "Relatórios — Demanda de matéria-prima",
    group: G,
    module: "reports",
    description:
      "Relatório consolidado de demanda de MP (baseado em pedidos de venda). Substitui nomenclatura legada proposals.material_report.view.",
    type: "section",
    parentKey: "reports.view",
    requires: ["reports.view"],
  }),
  perm({ key: "guide.view", label: "Guia do Sistema", group: G, module: "guide", description: "Acessar o guia funcional do sistema.", type: "menu" }),

  // —— Financeiro ——
  perm({
    key: "finance.view",
    label: "Financeiro",
    group: FIN,
    module: "finance",
    description: "Acessar o domínio Financeiro no menu principal.",
    type: "menu",
  }),
  perm({
    key: "finance.accountsReceivable.view",
    label: "Financeiro — Contas a Receber",
    group: FIN,
    module: "finance",
    description: "Consultar dashboard read-only de Contas a Receber (Nomus sync local).",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.accountsReceivable.export",
    label: "Financeiro — Exportar Contas a Receber",
    group: FIN,
    module: "finance",
    description: "Exportar CSV da carteira de Contas a Receber com filtros aplicados.",
    type: "action",
    parentKey: "finance.accountsReceivable.view",
    requires: ["finance.view", "finance.accountsReceivable.view"],
  }),
  perm({
    key: "finance.accountsPayable.view",
    label: "Financeiro — Contas a Pagar",
    group: FIN,
    module: "finance",
    description: "Consultar dashboard read-only de Contas a Pagar (Nomus sync local).",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.accountsPayable.export",
    label: "Financeiro — Exportar Contas a Pagar",
    group: FIN,
    module: "finance",
    description: "Exportar CSV da carteira de Contas a Pagar com filtros aplicados.",
    type: "action",
    parentKey: "finance.accountsPayable.view",
    requires: ["finance.view", "finance.accountsPayable.view"],
  }),
  perm({
    key: "finance.cashFlow.view",
    label: "Financeiro — Fluxo de Caixa",
    group: FIN,
    module: "finance",
    description: "Consultar Fluxo de Caixa (chave 1:1 P17; finance.view não abre o fluxo).",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.billing.view",
    label: "Financeiro — Faturamento",
    group: FIN,
    module: "finance",
    description: "Consultar faturamento / NF no domínio Financeiro (P17).",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.salesOrders.view",
    label: "Financeiro — Pedidos de Venda",
    group: FIN,
    module: "finance",
    description: "Consultar pedidos de venda na visão financeira (P17).",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.reports.view",
    label: "Financeiro — Relatórios",
    group: FIN,
    module: "finance",
    description: "Acessar relatórios financeiros (chave 1:1 P17; reports.view é mega).",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.cost_centers.view",
    label: "Financeiro — Ver centros de custo",
    group: FIN,
    module: "finance",
    description: "Consultar centros de custo financeiros para classificação gerencial de AP.",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.cost_centers.manage",
    label: "Financeiro — Gerenciar centros de custo",
    group: FIN,
    module: "finance",
    description: "Criar e editar centros de custo financeiros.",
    type: "action",
    parentKey: "finance.cost_centers.view",
    requires: ["finance.view", "finance.cost_centers.view"],
  }),
  perm({
    key: "finance.suppliers.view",
    label: "Financeiro — Ver fornecedores consolidados",
    group: FIN,
    module: "finance",
    description: "Consultar base consolidada de fornecedores derivada de Contas a Pagar.",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.suppliers.manage",
    label: "Financeiro — Gerenciar fornecedores consolidados",
    group: FIN,
    module: "finance",
    description: "Criar, editar e consolidar fornecedores e aliases.",
    type: "action",
    parentKey: "finance.suppliers.view",
    requires: ["finance.view", "finance.suppliers.view"],
  }),
  perm({
    key: "finance.suppliers.service_termination.view",
    label: "Financeiro — Ver encerramento de prestação",
    group: FIN,
    module: "finance",
    description:
      "Consultar cálculos gerenciais de encerramento de prestação de serviço de fornecedores/prestadores.",
    type: "action",
    parentKey: "finance.suppliers.view",
    requires: ["finance.view", "finance.suppliers.view"],
  }),
  perm({
    key: "finance.suppliers.service_termination.create",
    label: "Financeiro — Criar encerramento de prestação",
    group: FIN,
    module: "finance",
    description: "Criar e salvar prévia de encerramento de prestação de serviço.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.view",
    requires: ["finance.suppliers.service_termination.view"],
  }),
  perm({
    key: "finance.suppliers.service_termination.update",
    label: "Financeiro — Editar encerramento de prestação",
    group: FIN,
    module: "finance",
    description: "Alterar rascunhos de encerramento (não finalizados).",
    type: "action",
    parentKey: "finance.suppliers.service_termination.view",
    requires: ["finance.suppliers.service_termination.view"],
  }),
  perm({
    key: "finance.suppliers.service_termination.finalize",
    label: "Financeiro — Finalizar encerramento de prestação",
    group: FIN,
    module: "finance",
    description: "Finalizar e travar snapshot do encerramento de prestação.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.view",
    requires: ["finance.suppliers.service_termination.view"],
    risk: "sensitive",
  }),
  perm({
    key: "finance.suppliers.service_termination.export",
    label: "Financeiro — Exportar encerramento de prestação",
    group: FIN,
    module: "finance",
    description: "Gerar PDF/XLSX do encerramento de prestação de serviço.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.view",
    requires: ["finance.suppliers.service_termination.view"],
  }),
  perm({
    key: "finance.suppliers.service_termination.cancel",
    label: "Financeiro — Cancelar encerramento de prestação",
    group: FIN,
    module: "finance",
    description: "Cancelar rascunho de encerramento de prestação.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.view",
    requires: ["finance.suppliers.service_termination.view"],
    risk: "sensitive",
  }),
  /** Aliases documentados (mesmo efeito que finance.suppliers.service_termination.*). */
  perm({
    key: "suppliers.serviceTermination.view",
    label: "Fornecedores — Ver encerramento (alias)",
    group: FIN,
    module: "finance",
    description: "Alias de finance.suppliers.service_termination.view.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.view",
    requires: ["finance.suppliers.service_termination.view"],
  }),
  perm({
    key: "suppliers.serviceTermination.create",
    label: "Fornecedores — Criar encerramento (alias)",
    group: FIN,
    module: "finance",
    description: "Alias de finance.suppliers.service_termination.create.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.create",
    requires: ["finance.suppliers.service_termination.create"],
  }),
  perm({
    key: "suppliers.serviceTermination.update",
    label: "Fornecedores — Editar encerramento (alias)",
    group: FIN,
    module: "finance",
    description: "Alias de finance.suppliers.service_termination.update.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.update",
    requires: ["finance.suppliers.service_termination.update"],
  }),
  perm({
    key: "suppliers.serviceTermination.finalize",
    label: "Fornecedores — Finalizar encerramento (alias)",
    group: FIN,
    module: "finance",
    description: "Alias de finance.suppliers.service_termination.finalize.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.finalize",
    requires: ["finance.suppliers.service_termination.finalize"],
    risk: "sensitive",
  }),
  perm({
    key: "suppliers.serviceTermination.export",
    label: "Fornecedores — Exportar encerramento (alias)",
    group: FIN,
    module: "finance",
    description: "Alias de finance.suppliers.service_termination.export.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.export",
    requires: ["finance.suppliers.service_termination.export"],
  }),
  perm({
    key: "suppliers.serviceTermination.cancel",
    label: "Fornecedores — Cancelar encerramento (alias)",
    group: FIN,
    module: "finance",
    description: "Alias de finance.suppliers.service_termination.cancel.",
    type: "action",
    parentKey: "finance.suppliers.service_termination.cancel",
    requires: ["finance.suppliers.service_termination.cancel"],
    risk: "sensitive",
  }),
  perm({
    key: "finance.executiveReport.view",
    label: "Financeiro — Relatório Presidencial",
    group: FIN,
    module: "finance",
    description: "Consultar o relatório executivo / presidencial financeiro.",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
    risk: "sensitive",
  }),
  perm({
    key: "finance.dre.view",
    label: "Financeiro — DRE Gerencial Mensal",
    group: FIN,
    module: "finance",
    description: "Consultar o DRE gerencial mensal (NF-e, centros de custo e CMV oficial).",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
    risk: "sensitive",
  }),
  perm({
    key: "finance.cost_center_rules.view",
    label: "Financeiro — Ver regras de classificação",
    group: FIN,
    module: "finance",
    description: "Consultar regras fornecedor → centro de custo.",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.cost_center_rules.manage",
    label: "Financeiro — Gerenciar regras de classificação",
    group: FIN,
    module: "finance",
    description: "Criar e editar regras de classificação automática por fornecedor.",
    type: "action",
    parentKey: "finance.cost_center_rules.view",
    requires: ["finance.view", "finance.cost_center_rules.view"],
  }),
  perm({
    key: "finance.ap_allocations.view",
    label: "Financeiro — Ver classificação de títulos AP",
    group: FIN,
    module: "finance",
    description: "Consultar alocações de centro de custo em títulos de Contas a Pagar.",
    type: "section",
    parentKey: "finance.accountsPayable.view",
    requires: ["finance.view", "finance.accountsPayable.view"],
  }),
  perm({
    key: "finance.ap_allocations.manage",
    label: "Financeiro — Classificar títulos AP",
    group: FIN,
    module: "finance",
    description: "Classificar manualmente títulos de Contas a Pagar em centros de custo.",
    type: "action",
    parentKey: "finance.ap_allocations.view",
    requires: ["finance.view", "finance.accountsPayable.view", "finance.ap_allocations.view"],
  }),
  perm({
    key: "finance.ap_allocations.apply_batch",
    label: "Financeiro — Classificação em lote AP",
    group: FIN,
    module: "finance",
    description: "Aplicar classificação em lote em títulos de Contas a Pagar.",
    type: "action",
    parentKey: "finance.ap_allocations.manage",
    requires: [
      "finance.view",
      "finance.accountsPayable.view",
      "finance.ap_allocations.view",
      "finance.ap_allocations.manage",
    ],
    risk: "sensitive",
  }),
  perm({
    key: "finance.cost_center_audit.view",
    label: "Financeiro — Auditoria de classificação",
    group: FIN,
    module: "finance",
    description: "Consultar log de auditoria de fornecedores, regras e alocações de centro de custo.",
    type: "section",
    parentKey: "finance.ap_allocations.view",
    requires: ["finance.view", "finance.ap_allocations.view"],
  }),
  perm({
    key: "finance.portfolioReconciliation.view",
    label: "Financeiro — Conciliação de Carteira",
    group: FIN,
    module: "portfolio-reconciliation",
    description:
      "Acessar o módulo Conciliação de Carteira (auditoria paralela Pedido → documento → CR). Não altera Fluxo/CR oficial.",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.portfolioReconciliation.conciliation.view",
    label: "Conciliação de Carteira — aba Conciliação",
    group: FIN,
    module: "portfolio-reconciliation",
    description: "Visualizar a aba Conciliação (cards, comparison e tabela de pedidos).",
    type: "tab",
    parentKey: "finance.portfolioReconciliation.view",
    requires: ["finance.view", "finance.portfolioReconciliation.view"],
  }),
  perm({
    key: "finance.portfolioReconciliation.intelligence.view",
    label: "Conciliação de Carteira — aba Inteligência",
    group: FIN,
    module: "portfolio-reconciliation",
    description: "Visualizar a aba Inteligência da Carteira (maturidade / board O2C).",
    type: "tab",
    parentKey: "finance.portfolioReconciliation.view",
    requires: ["finance.view", "finance.portfolioReconciliation.view"],
  }),
  perm({
    key: "finance.portfolioReconciliation.orderToCashAudit.view",
    label: "Conciliação de Carteira — aba Auditoria Pedido → Caixa",
    group: FIN,
    module: "portfolio-reconciliation",
    description: "Visualizar a aba Auditoria Pedido → Caixa (OrderToCashAudit materializado).",
    type: "tab",
    parentKey: "finance.portfolioReconciliation.view",
    requires: ["finance.view", "finance.portfolioReconciliation.view"],
  }),
  perm({
    key: "finance.portfolioReconciliation.orderStatusPedidos.view",
    label: "Conciliação de Carteira — aba Status Pedidos",
    group: FIN,
    module: "portfolio-reconciliation",
    description:
      "Visualizar a aba Status Pedidos (consolidado por Pedido de Venda sobre OrderToCashAudit).",
    type: "tab",
    parentKey: "finance.portfolioReconciliation.view",
    requires: ["finance.view", "finance.portfolioReconciliation.view"],
  }),

  // —— Comercial (shell do grupo) ——
  perm({
    key: "commercial.view",
    label: "Comercial",
    group: CRM,
    module: "crm-commercial",
    description:
      "Shell do grupo Comercial (chave 1:1 do parent; não substitui Pedidos/CRM).",
    type: "menu",
  }),

  // —— CRM ——
  perm({ key: "crm.view", label: "CRM Comercial", group: CRM, module: "crm-commercial", description: "Acessar o módulo CRM Comercial.", type: "menu" }),
  perm({
    key: "crm.general.view",
    label: "CRM — Gestão Geral",
    group: CRM,
    module: "crm-commercial",
    description: "Aba de gestão comercial geral.",
    type: "tab",
    parentKey: "crm.view",
    requires: ["crm.view"],
  }),
  perm({
    key: "crm.seller.view",
    label: "CRM — Gestão por Responsável",
    group: CRM,
    module: "crm-commercial",
    description: "Aba de gestão por vendedor.",
    type: "tab",
    parentKey: "crm.view",
    requires: ["crm.view"],
  }),
  perm({
    key: "crm.seller.all",
    label: "CRM — Ver todos os vendedores",
    group: CRM,
    module: "crm-commercial",
    description: "Ver dados de todos os vendedores.",
    type: "action",
    parentKey: "crm.seller.view",
    requires: ["crm.view", "crm.seller.view"],
    risk: "sensitive",
  }),
  perm({
    key: "crm.seller.own",
    label: "CRM — Ver somente próprio vendedor",
    group: CRM,
    module: "crm-commercial",
    description: "Ver apenas dados do vendedor vinculado.",
    type: "action",
    parentKey: "crm.seller.view",
    requires: ["crm.view", "crm.seller.view"],
  }),
  perm({
    key: "crm.customer_cockpit.view",
    label: "CRM — Cockpit do Cliente",
    group: CRM,
    module: "crm-commercial",
    description: "Carteira e cockpit do cliente no CRM.",
    type: "section",
    parentKey: "crm.view",
    requires: ["crm.view"],
  }),
  perm({
    key: "crm.activities.create",
    label: "CRM — Criar atividade/contato",
    group: CRM,
    module: "crm-commercial",
    description: "Registrar atividades e contatos.",
    type: "action",
    parentKey: "crm.customer_cockpit.view",
    requires: ["crm.view", "crm.customer_cockpit.view"],
  }),
  perm({
    key: "crm.activities.edit",
    label: "CRM — Editar/concluir atividade",
    group: CRM,
    module: "crm-commercial",
    description: "Editar ou concluir atividades.",
    type: "action",
    parentKey: "crm.customer_cockpit.view",
    requires: ["crm.view", "crm.customer_cockpit.view"],
  }),
  perm({
    key: "crm.profile.edit",
    label: "CRM — Editar perfil comercial do cliente",
    group: CRM,
    module: "crm-commercial",
    description: "Editar perfil de relacionamento comercial.",
    type: "action",
    parentKey: "crm.customer_cockpit.view",
    requires: ["crm.view", "crm.customer_cockpit.view"],
  }),
  perm({
    key: "crm.customers.assign_seller",
    label: "CRM — Definir responsável comercial do cliente",
    group: CRM,
    module: "crm-commercial",
    description: "Alterar o vendedor/responsável comercial no cadastro do cliente.",
    type: "action",
    parentKey: "crm.customer_cockpit.view",
    requires: ["crm.view", "crm.customer_cockpit.view"],
    risk: "sensitive",
  }),

  // —— Clientes ——
  perm({ key: "customers.view", label: "Clientes", group: CLI, module: "customers", description: "Consultar clientes.", type: "menu" }),
  perm({
    key: "customers.create",
    label: "Clientes — Criar",
    group: CLI,
    module: "customers",
    description: "Cadastrar novos clientes.",
    type: "action",
    parentKey: "customers.view",
    requires: ["customers.view"],
  }),
  perm({
    key: "customers.edit",
    label: "Clientes — Editar",
    group: CLI,
    module: "customers",
    description: "Editar cadastro de clientes.",
    type: "action",
    parentKey: "customers.view",
    requires: ["customers.view"],
  }),
  perm({
    key: "customers.commercial360.view",
    label: "Clientes — Visão Comercial 360",
    group: CLI,
    module: "customers",
    description: "Visão comercial ampliada do cliente.",
    type: "section",
    parentKey: "customers.view",
    requires: ["customers.view"],
  }),

  // —— Propostas ——
  perm({ key: "proposals.view", label: "Propostas", group: PROP, module: "proposals", description: "Consultar propostas.", type: "menu" }),
  perm({
    key: "proposals.create",
    label: "Propostas — Criar",
    group: PROP,
    module: "proposals",
    description: "Criar novas propostas.",
    type: "action",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),
  perm({
    key: "proposals.edit",
    label: "Propostas — Editar",
    group: PROP,
    module: "proposals",
    description: "Editar propostas existentes.",
    type: "action",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),
  perm({
    key: "proposals.delete",
    label: "Propostas — Excluir",
    group: PROP,
    module: "proposals",
    description: "Excluir propostas.",
    type: "action",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
    risk: "critical",
  }),
  perm({
    key: "proposals.print",
    label: "Propostas — Imprimir/gerar cliente",
    group: PROP,
    module: "proposals",
    description: "Imprimir ou gerar versão para o cliente.",
    type: "action",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),
  perm({
    key: "proposals.indicators.view",
    label: "Propostas — Indicadores",
    group: PROP,
    module: "proposals",
    description: "Indicadores e análises de propostas.",
    type: "tab",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),
  perm({
    key: "proposals.material_report.view",
    label: "Propostas — Relatório Geral de MP (legado)",
    group: PROP,
    module: "proposals",
    description:
      "LEGADO — alias de reports.material_demand.view. Mantido por compatibilidade com perfis existentes.",
    type: "section",
    parentKey: "proposals.view",
    requires: ["proposals.view"],
  }),

  // —— Pedidos ——
  perm({ key: "sales_orders.view", label: "Pedidos de venda", group: SO, module: "sales-orders", description: "Consultar pedidos de venda.", type: "menu" }),
  perm({
    key: "sales_orders.detail.view",
    label: "Pedidos — Detalhe",
    group: SO,
    module: "sales-orders",
    description: "Visualizar detalhes do pedido.",
    type: "section",
    parentKey: "sales_orders.view",
    requires: ["sales_orders.view"],
  }),
  perm({
    key: "sales_orders.invoice.view",
    label: "Pedidos — Faturamento/NFe",
    group: SO,
    module: "sales-orders",
    description: "Informações de faturamento e NFe.",
    type: "section",
    parentKey: "sales_orders.view",
    requires: ["sales_orders.view"],
  }),
  perm({
    key: "sales_orders.flow.view",
    label: "Pedidos — Visualizar Fluxo",
    group: SO,
    module: "sales-orders",
    description: "Visualizar Kanban e etapa operacional do Fluxo de Pedidos.",
    type: "section",
    parentKey: "sales_orders.view",
    requires: ["sales_orders.view"],
  }),
  perm({
    key: "sales_orders.flow.values.view",
    label: "Pedidos — Fluxo — Valores",
    group: SO,
    module: "sales-orders",
    description: "Visualizar valores comerciais no Fluxo de Pedidos.",
    type: "section",
    parentKey: "sales_orders.flow.view",
    requires: ["sales_orders.view", "sales_orders.flow.view"],
    risk: "sensitive",
  }),
  perm({
    key: "sales_orders.flow.financial.view",
    label: "Pedidos — Fluxo — Financeiro",
    group: SO,
    module: "sales-orders",
    description:
      "Visualizar situação financeira consolidada no Fluxo de Pedidos.",
    type: "section",
    parentKey: "sales_orders.flow.view",
    requires: ["sales_orders.view", "sales_orders.flow.view"],
    risk: "sensitive",
  }),
  perm({
    key: "sales_orders.flow.inconsistencies.view",
    label: "Pedidos — Fluxo — Inconsistências",
    group: SO,
    module: "sales-orders",
    description: "Visualizar inconsistências detectadas no Fluxo de Pedidos.",
    type: "section",
    parentKey: "sales_orders.flow.view",
    requires: ["sales_orders.view", "sales_orders.flow.view"],
  }),
  perm({
    key: "sales_orders.flow.timeline.view",
    label: "Pedidos — Fluxo — Timeline",
    group: SO,
    module: "sales-orders",
    description: "Visualizar eventos e histórico do Fluxo de Pedidos.",
    type: "section",
    parentKey: "sales_orders.flow.view",
    requires: ["sales_orders.view", "sales_orders.flow.view"],
    risk: "sensitive",
  }),
  perm({
    key: "sales_orders.flow_management.manage",
    label: "Pedidos — Gestão do fluxo",
    group: SO,
    module: "sales-orders",
    description:
      "Definir prioridade, responsável, área, bloqueio, previsão e nota interna do Fluxo de Pedidos (sem alterar estágio).",
    type: "action",
    parentKey: "sales_orders.view",
    requires: ["sales_orders.view"],
    risk: "sensitive",
  }),
  perm({
    key: "sales_orders.flow_management.priority.manage",
    label: "Pedidos — Fluxo — Alterar prioridade",
    group: SO,
    module: "sales-orders",
    description: "Alterar a prioridade manual do Fluxo de Pedidos.",
    type: "action",
    parentKey: "sales_orders.flow_management.manage",
    requires: [
      "sales_orders.view",
      "sales_orders.flow.view",
      "sales_orders.flow_management.manage",
    ],
    risk: "sensitive",
  }),
  perm({
    key: "sales_orders.flow_management.responsibility.manage",
    label: "Pedidos — Fluxo — Atribuir responsável",
    group: SO,
    module: "sales-orders",
    description: "Atribuir responsável e área no Fluxo de Pedidos.",
    type: "action",
    parentKey: "sales_orders.flow_management.manage",
    requires: [
      "sales_orders.view",
      "sales_orders.flow.view",
      "sales_orders.flow_management.manage",
    ],
    risk: "sensitive",
  }),
  perm({
    key: "sales_orders.flow_management.blocking.manage",
    label: "Pedidos — Fluxo — Gerenciar bloqueio",
    group: SO,
    module: "sales-orders",
    description:
      "Registrar ou remover bloqueio e definir previsão de resolução.",
    type: "action",
    parentKey: "sales_orders.flow_management.manage",
    requires: [
      "sales_orders.view",
      "sales_orders.flow.view",
      "sales_orders.flow_management.manage",
    ],
    risk: "sensitive",
  }),
  perm({
    key: "sales_orders.flow.rebuild.execute",
    label: "Pedidos — Fluxo — Executar rebuild",
    group: SO,
    module: "sales-orders",
    description:
      "Executar administrativamente o rebuild dos snapshots do Fluxo de Pedidos.",
    type: "action",
    parentKey: "sales_orders.flow.view",
    requires: ["sales_orders.view", "sales_orders.flow.view"],
    risk: "critical",
  }),

  // —— Documentos de Saída ——
  perm({
    key: "output_documents.view",
    label: "Documentos de Saída",
    group: SO,
    module: "output-documents",
    description: "Consultar lista e resumo de Documentos de Saída.",
    type: "menu",
  }),
  perm({
    key: "output_documents.detail.view",
    label: "Documentos de Saída — Detalhe",
    group: SO,
    module: "output-documents",
    description: "Visualizar detalhe geral e itens.",
    type: "section",
    parentKey: "output_documents.view",
    requires: ["output_documents.view"],
  }),
  perm({
    key: "output_documents.financial.view",
    label: "Documentos de Saída — Financeiro",
    group: SO,
    module: "output-documents",
    description: "Visualizar seção financeira (CR) do detalhe.",
    type: "section",
    parentKey: "output_documents.view",
    requires: ["output_documents.view"],
  }),
  perm({
    key: "output_documents.audit.view",
    label: "Documentos de Saída — Auditoria",
    group: SO,
    module: "output-documents",
    description: "Visualizar seção de auditoria/vínculos do detalhe.",
    type: "section",
    parentKey: "output_documents.view",
    requires: ["output_documents.view"],
  }),
  perm({
    key: "output_documents.raw.view",
    label: "Documentos de Saída — rawJson",
    group: SO,
    module: "output-documents",
    description: "Acesso técnico ao rawJson do stage (gated).",
    type: "action",
    parentKey: "output_documents.view",
    requires: ["output_documents.view"],
  }),
  perm({
    key: "audit.raw.read",
    label: "Auditoria — leitura de raw técnico",
    group: SO,
    module: "output-documents",
    description: "Alias técnico para raw de auditoria (Documentos de Saída / Order Full Audit).",
    type: "action",
  }),

  // —— Engenharia / Produtos ——
  perm({ key: "products.view", label: "Engenharia / Produtos", group: ENG, module: "products", description: "Consultar produtos e engenharia.", type: "menu" }),
  perm({
    key: "products.create",
    label: "Engenharia — Criar item",
    group: ENG,
    module: "products",
    description: "Criar produtos ou componentes.",
    type: "action",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.edit",
    label: "Engenharia — Editar item",
    group: ENG,
    module: "products",
    description: "Editar produtos ou componentes.",
    type: "action",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.delete",
    label: "Engenharia — Excluir item",
    group: ENG,
    module: "products",
    description: "Excluir itens de engenharia.",
    type: "action",
    parentKey: "products.view",
    requires: ["products.view"],
    risk: "critical",
  }),
  perm({
    key: "products.export.engineering",
    label: "Engenharia — Exportar layout",
    group: ENG,
    module: "products",
    description: "Exportar planilha de engenharia.",
    type: "action",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.info",
    label: "Engenharia — Aba Informações",
    group: ENG,
    module: "products",
    description: "Aba de identificação do produto.",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.bom",
    label: "Engenharia — Aba Estrutura BOM",
    group: ENG,
    module: "products",
    description: "Aba de estrutura (BOM).",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.routing",
    label: "Engenharia — Aba Processo/Roteiro",
    group: ENG,
    module: "products",
    description: "Aba de roteiro de processo.",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.tree",
    label: "Engenharia — Aba Estrutura em Árvore",
    group: ENG,
    module: "products",
    description: "Aba de estrutura em árvore.",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
  }),
  perm({
    key: "products.tab.cost",
    label: "Engenharia — Aba Análise de Custo",
    group: ENG,
    module: "products",
    description: "Aba de análise de custo.",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
    risk: "sensitive",
  }),
  perm({
    key: "products.tab.composition",
    label: "Engenharia — Aba Composição de Custos",
    group: ENG,
    module: "products",
    description: "Aba de composição de custos (open book).",
    type: "tab",
    parentKey: "products.view",
    requires: ["products.view"],
    risk: "sensitive",
  }),

  // —— Compras ——
  perm({ key: "purchases.view", label: "Compras", group: COMP, module: "purchases", description: "Consultar solicitações de compra.", type: "menu" }),
  perm({
    key: "purchases.create",
    label: "Compras — Criar solicitação",
    group: COMP,
    module: "purchases",
    description: "Criar solicitações de compra.",
    type: "action",
    parentKey: "purchases.view",
    requires: ["purchases.view"],
  }),
  perm({
    key: "purchases.edit",
    label: "Compras — Editar solicitação",
    group: COMP,
    module: "purchases",
    description: "Editar solicitações de compra.",
    type: "action",
    parentKey: "purchases.view",
    requires: ["purchases.view"],
  }),
  perm({
    key: "purchases.delete",
    label: "Compras — Excluir/cancelar",
    group: COMP,
    module: "purchases",
    description: "Cancelar ou excluir solicitações.",
    type: "action",
    parentKey: "purchases.view",
    requires: ["purchases.view"],
    risk: "critical",
  }),
  perm({
    key: "purchases.indicators.view",
    label: "Compras — Indicadores",
    group: COMP,
    module: "purchases",
    description: "Indicadores do módulo de compras.",
    type: "section",
    parentKey: "purchases.view",
    requires: ["purchases.view"],
  }),

  // —— Precificação / Impostos ——
  perm({
    key: "price_table.view",
    label: "Tabela comercial",
    group: PRC,
    module: "commercial-price-table",
    description: "Consultar preços comerciais publicados vigentes.",
    type: "menu",
  }),
  perm({ key: "pricing.view", label: "Formação de Preço", group: PRC, module: "pricing", description: "Acessar formação de preço.", type: "menu" }),
  perm({
    key: "pricing.simulate",
    label: "Precificação — Simular preço",
    group: PRC,
    module: "pricing",
    description: "Simular preços unitários ou em lote.",
    type: "action",
    parentKey: "pricing.view",
    requires: ["pricing.view"],
  }),
  perm({
    key: "pricing.generate_tables",
    label: "Precificação — Gerar tabelas comerciais",
    group: PRC,
    module: "pricing",
    description: "Gerar versões DRAFT de tabelas comerciais.",
    type: "action",
    parentKey: "pricing.view",
    requires: ["pricing.view"],
    risk: "sensitive",
  }),
  perm({
    key: "pricing.publish_tables",
    label: "Precificação — Publicar tabelas",
    group: PRC,
    module: "pricing",
    description: "Publicar versões de tabelas comerciais.",
    type: "action",
    parentKey: "pricing.view",
    requires: ["pricing.view"],
    risk: "critical",
  }),
  perm({ key: "taxes.view", label: "Regras fiscais", group: PRC, module: "taxes", description: "Consultar regras fiscais de precificação.", type: "menu" }),
  perm({
    key: "taxes.edit",
    label: "Regras fiscais — Editar",
    group: PRC,
    module: "taxes",
    description: "Editar regras fiscais de precificação.",
    type: "action",
    parentKey: "taxes.view",
    requires: ["taxes.view"],
    risk: "sensitive",
  }),
  perm({
    key: "finance.tax_apuration.view",
    label: "Financeiro — Apuração e guias fiscais",
    group: FIN,
    module: "finance",
    description:
      "Consultar apuração por período, guias de recolhimento (DARF/GNRE/…) e comprovantes. Não inclui regras de precificação.",
    type: "section",
    parentKey: "finance.view",
    requires: ["finance.view"],
  }),
  perm({
    key: "finance.tax_apuration.manage",
    label: "Financeiro — Gerenciar apuração/guias",
    group: FIN,
    module: "finance",
    description: "Criar/editar apuração, guias, baixas e comprovantes fiscais.",
    type: "action",
    parentKey: "finance.tax_apuration.view",
    requires: ["finance.view", "finance.tax_apuration.view"],
    risk: "sensitive",
  }),
  perm({
    key: "finance.tax_allocation.manage",
    label: "Financeiro — Alocação gerencial de recolhimento",
    group: FIN,
    module: "finance",
    description:
      "Alocar parcelas de recolhimento a pedidos/NFs (camada gerencial — nunca pagamento oficial da NF).",
    type: "action",
    parentKey: "finance.tax_apuration.view",
    requires: ["finance.view", "finance.tax_apuration.view"],
    risk: "sensitive",
  }),

  // —— Custos / Operação ——
  perm({ key: "employees.view", label: "Pessoas / RH", group: OPS, module: "employees", description: "Consultar colaboradores (módulo administrativo de RH).", type: "menu" }),
  perm({
    key: "employees.dashboard.view",
    label: "Pessoas / RH — Dashboard",
    group: OPS,
    module: "employees",
    description:
      "Dashboard executivo de headcount e custo estimado RH. Valores em R$ exigem também dados sensíveis.",
    type: "menu",
    parentKey: "employees.view",
    requires: ["employees.view"],
  }),
  perm({
    key: "employees.edit",
    label: "Pessoas / RH — Editar",
    group: OPS,
    module: "employees",
    description: "Editar colaboradores no módulo administrativo de RH (legado amplo; implica facetas finas).",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "sensitive",
  }),
  perm({
    key: "employees.create",
    label: "Pessoas / RH — Criar colaborador",
    group: OPS,
    module: "employees",
    description: "Criar colaborador. Quem já tem employees.edit continua com acesso efetivo.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "sensitive",
  }),
  perm({
    key: "employees.personal_data.view",
    label: "Pessoas / RH — Dados pessoais",
    group: OPS,
    module: "employees",
    description: "Ver dados pessoais da ficha (CPF, telefone, e-mail pessoal, endereço).",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "sensitive",
  }),
  perm({
    key: "employees.administrative_data.view",
    label: "Pessoas / RH — Dados administrativos",
    group: OPS,
    module: "employees",
    description: "Ver referência administrativa e observações administrativas.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "sensitive",
  }),
  perm({
    key: "employees.sensitive_data.view",
    label: "Pessoas / RH — Dados sensíveis",
    group: OPS,
    module: "employees",
    description: "Ver salário, custos HH e contatos de emergência.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "critical",
  }),
  perm({
    key: "employees.links.view",
    label: "Pessoas / RH — Ver vínculos",
    group: OPS,
    module: "employees",
    description: "Consultar vínculos no sistema da ficha do colaborador.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
  }),
  perm({
    key: "employees.links.manage",
    label: "Pessoas / RH — Gerenciar vínculos",
    group: OPS,
    module: "employees",
    description: "Vincular/desvincular pessoa canônica na ficha de RH.",
    type: "action",
    parentKey: "employees.links.view",
    requires: ["employees.links.view"],
    risk: "sensitive",
  }),
  perm({
    key: "employees.user_link.manage",
    label: "Pessoas / RH — Vínculo com usuário",
    group: OPS,
    module: "employees",
    description: "Vincular/desvincular AppUser ao colaborador.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "sensitive",
  }),
  perm({
    key: "employees.epi.manage",
    label: "Pessoas / RH — EPI / uniformes",
    group: OPS,
    module: "employees",
    description: "Alterar tamanhos e notas de EPI/uniforme.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
  }),
  perm({
    key: "people.search",
    label: "Pessoas — Pesquisar identidade canônica",
    group: OPS,
    module: "employees",
    description: "Pesquisar pessoa canônica e papéis vinculados (colaborador, usuário, comissão, etc.).",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
  }),
  perm({
    key: "people.link.manage",
    label: "Pessoas — Gerenciar vínculos de identidade",
    group: OPS,
    module: "employees",
    description: "Criar e remover vínculos Person ↔ papéis de domínio.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "sensitive",
  }),
  perm({
    key: "people.pii.view",
    label: "Pessoas — Ver dados pessoais (e-mail/CPF)",
    group: OPS,
    module: "employees",
    description: "Visualizar e-mail e CPF sem máscara nas buscas de pessoa canônica.",
    type: "action",
    parentKey: "employees.view",
    requires: ["employees.view"],
    risk: "sensitive",
  }),
  perm({ key: "machines.view", label: "Máquinas", group: OPS, module: "machines", description: "Consultar máquinas.", type: "menu" }),
  perm({
    key: "machines.edit",
    label: "Máquinas — Editar",
    group: OPS,
    module: "machines",
    description: "Editar máquinas e centros de trabalho.",
    type: "action",
    parentKey: "machines.view",
    requires: ["machines.view"],
  }),
  perm({
    key: "operations.component-performance.view",
    label: "Operações — Performance de componentes",
    group: OPS,
    module: "operations-performance",
    description:
      "Consultar componentes e histórico de alterações de performance produtiva (ciclo, cavidades).",
    type: "menu",
  }),
  perm({
    key: "operations.component-performance.edit",
    label: "Operações — Alterar performance de componentes",
    group: OPS,
    module: "operations-performance",
    description:
      "Registrar alterações operacionais de ciclo, cavidades e demais parâmetros produtivos de componentes.",
    type: "action",
    parentKey: "operations.component-performance.view",
    requires: ["operations.component-performance.view"],
  }),
  perm({
    key: "operations.production-orders.view",
    label: "Operações — Ordens de Produção",
    group: OPS,
    module: "production-orders",
    description:
      "Consultar Ordens de Produção sincronizadas do Nomus (stage local, somente leitura).",
    type: "menu",
  }),
  perm({
    key: "engineering.view",
    label: "Engenharia",
    group: OPS,
    module: "engineering",
    description: "Grupo Engenharia (accordion) — chave 1:1 P19.",
    type: "menu",
  }),
  perm({ key: "materials.view", label: "Materiais", group: OPS, module: "materials", description: "Consultar materiais.", type: "menu" }),
  perm({
    key: "materials.edit",
    label: "Materiais — Editar",
    group: OPS,
    module: "materials",
    description: "Editar materiais e suprimentos.",
    type: "action",
    parentKey: "materials.view",
    requires: ["materials.view"],
  }),
  perm({
    key: "materials.market_intelligence.view",
    label: "Inteligência de Mercado",
    group: OPS,
    module: "materials",
    description: "Acessar Inteligência de Mercado (chave 1:1 P19).",
    type: "section",
    parentKey: "materials.view",
    requires: ["materials.view"],
  }),
  perm({
    key: "materials.market_intelligence.home.view",
    label: "IM — Home",
    group: OPS,
    module: "materials",
    description: "Aba Home da Inteligência de Mercado.",
    type: "action",
    parentKey: "materials.market_intelligence.view",
    requires: ["materials.market_intelligence.view"],
  }),
  perm({
    key: "materials.market_intelligence.material_360.view",
    label: "IM — Matéria-prima 360",
    group: OPS,
    module: "materials",
    description: "Aba Matéria-prima 360.",
    type: "action",
    parentKey: "materials.market_intelligence.view",
    requires: ["materials.market_intelligence.view"],
  }),
  perm({
    key: "materials.market_intelligence.quotes.view",
    label: "IM — Cotações",
    group: OPS,
    module: "materials",
    description: "Aba Cotações / fornecedores.",
    type: "action",
    parentKey: "materials.market_intelligence.view",
    requires: ["materials.market_intelligence.view"],
  }),
  perm({
    key: "transformation_simulator.view",
    label: "Simulador de Injeção",
    group: OPS,
    module: "transformation-simulator",
    description: "Consultar simulador de custo de injeção (chave 1:1 P19).",
    type: "menu",
  }),
  perm({
    key: "finance.accountsReceivable.sync",
    label: "Financeiro — Sync Contas a Receber",
    group: FIN,
    module: "finance",
    description: "Executar sync Nomus de Contas a Receber (chave 1:1 P19).",
    type: "action",
    parentKey: "finance.accountsReceivable.view",
    requires: ["finance.accountsReceivable.view"],
  }),
  perm({
    key: "finance.accountsPayable.sync",
    label: "Financeiro — Sync Contas a Pagar",
    group: FIN,
    module: "finance",
    description: "Executar sync Nomus de Contas a Pagar (chave 1:1 P19).",
    type: "action",
    parentKey: "finance.accountsPayable.view",
    requires: ["finance.accountsPayable.view"],
  }),
  perm({
    key: "finance.billing.sync",
    label: "Financeiro — Sync Faturamento",
    group: FIN,
    module: "finance",
    description: "Executar sync NF / faturamento (chave 1:1 P19).",
    type: "action",
    parentKey: "finance.billing.view",
    requires: ["finance.billing.view"],
  }),
  perm({
    key: "materials.market_quote.manual_exchange",
    label: "Cotação — Câmbio manual",
    group: OPS,
    module: "materials",
    description:
      "Informar taxa de câmbio manual (PTAX venda) em cotações USD quando a API do BCB falhar ou por exceção autorizada.",
    type: "action",
    parentKey: "materials.edit",
    requires: ["materials.edit"],
    risk: "sensitive",
  }),
  perm({
    key: "materials.market_quote.approve",
    label: "Cotação — Aprovar oficial",
    group: OPS,
    module: "materials",
    description:
      "Aprovar ou rejeitar cotações de matérias de criticidade Alta/Crítica antes de torná-las oficiais.",
    type: "action",
    parentKey: "materials.edit",
    requires: ["materials.edit"],
    risk: "sensitive",
  }),
  perm({ key: "opex.view", label: "Custos indiretos / OPEX", group: OPS, module: "opex", description: "Consultar custos indiretos.", type: "menu" }),
  perm({
    key: "opex.edit",
    label: "OPEX — Editar",
    group: OPS,
    module: "opex",
    description: "Editar custos indiretos.",
    type: "action",
    parentKey: "opex.view",
    requires: ["opex.view"],
    risk: "sensitive",
  }),
  perm({ key: "simulations.view", label: "Simulações", group: OPS, module: "simulations", description: "Consultar simulações.", type: "menu" }),
  perm({
    key: "simulations.create",
    label: "Simulações — Criar",
    group: OPS,
    module: "simulations",
    description: "Criar cenários de simulação.",
    type: "action",
    parentKey: "simulations.view",
    requires: ["simulations.view"],
  }),
  /** Legado: pacote único de custos (compatibilidade 1K-D). */
  perm({
    key: "costs.view",
    label: "Custos — visualizar (legado)",
    group: OPS,
    module: "costs",
    description: "Permissão legada que libera módulos de custo/operação. Prefira permissões específicas por módulo.",
    type: "menu",
    risk: "sensitive",
  }),

  // —— Configurações ——
  perm({ key: "settings.view", label: "Configurações", group: SYS, module: "settings", description: "Acessar configurações do sistema.", type: "menu" }),
  perm({
    key: "users.manage",
    label: "Usuários e Permissões",
    group: SYS,
    module: "settings",
    description: "Cadastrar e administrar usuários.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
    risk: "critical",
  }),
  perm({
    key: "accessProfiles.view",
    label: "Perfis de Acesso — visualizar",
    group: SYS,
    module: "settings",
    description: "Consultar perfis de acesso cadastrados.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
    risk: "sensitive",
  }),
  perm({
    key: "accessProfiles.manage",
    label: "Perfis de Acesso — gerenciar",
    group: SYS,
    module: "settings",
    description: "Criar, editar, duplicar e inativar perfis de acesso.",
    type: "action",
    parentKey: "accessProfiles.view",
    requires: ["accessProfiles.view", "settings.view"],
    risk: "critical",
  }),
  perm({
    key: "settings.branding.view",
    label: "Configurações — Marca/identidade",
    group: SYS,
    module: "settings",
    description: "Visualizar identidade visual.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
  }),
  perm({
    key: "settings.branding.edit",
    label: "Configurações — Editar marca/identidade",
    group: SYS,
    module: "settings",
    description: "Editar logos e identidade.",
    type: "action",
    parentKey: "settings.branding.view",
    requires: ["settings.view", "settings.branding.view"],
  }),
  perm({
    key: "settings.global_params.view",
    label: "Configurações — Parâmetros globais",
    group: SYS,
    module: "settings",
    description: "Visualizar parâmetros globais.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
    risk: "sensitive",
  }),
  perm({
    key: "settings.global_params.edit",
    label: "Configurações — Editar parâmetros globais",
    group: SYS,
    module: "settings",
    description: "Editar parâmetros globais de cálculo.",
    type: "action",
    parentKey: "settings.global_params.view",
    requires: ["settings.view", "settings.global_params.view"],
    risk: "critical",
  }),
  perm({
    key: "settings.nomus.view",
    label: "Configurações — Integração Nomus",
    group: SYS,
    module: "settings",
    description: "Visualizar logs e integração Nomus.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
    risk: "sensitive",
  }),
  perm({
    key: "settings.nomus.sync",
    label: "Configurações — Executar sincronização Nomus",
    group: SYS,
    module: "settings",
    description: "Disparar sincronização com Nomus.",
    type: "action",
    parentKey: "settings.nomus.view",
    requires: ["settings.view", "settings.nomus.view"],
    risk: "critical",
  }),
  perm({
    key: "settings.price_tables.view",
    label: "Configurações — Tabelas de preço",
    group: SYS,
    module: "settings",
    description: "Visualizar tabelas de preço comerciais.",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
  }),
  perm({
    key: "settings.price_tables.manage",
    label: "Configurações — Gerenciar tabelas de preço",
    group: SYS,
    module: "settings",
    description: "Gerenciar versões e itens de tabelas.",
    type: "action",
    parentKey: "settings.price_tables.view",
    requires: ["settings.view", "settings.price_tables.view"],
    risk: "critical",
  }),
  perm({
    key: "settings.operational.view",
    label: "Configurações — Operacional",
    group: SYS,
    module: "settings",
    description: "Visualizar estrutura operacional (cargos, encargos).",
    type: "section",
    parentKey: "settings.view",
    requires: ["settings.view"],
  }),
  perm({
    key: "settings.operational.manage",
    label: "Configurações — Gerenciar operacional",
    group: SYS,
    module: "settings",
    description: "Editar cargos, encargos e benefícios.",
    type: "action",
    parentKey: "settings.operational.view",
    requires: ["settings.view", "settings.operational.view"],
    risk: "sensitive",
  }),

  // —— Projetos ——
  perm({
    key: "projects.view",
    label: "Projetos",
    group: PRJ,
    module: "projects",
    description: "Acessar orçamentos técnicos e simulações de novos produtos, componentes e moldes.",
    type: "menu",
  }),
  perm({
    key: "projects.manage",
    label: "Projetos — Gerenciar",
    group: PRJ,
    module: "projects",
    description: "Criar e editar projetos, versões, estruturas simuladas e moldes.",
    type: "action",
    parentKey: "projects.view",
    requires: ["projects.view"],
  }),
  perm({
    key: "projects.approve",
    label: "Projetos — Aprovar",
    group: PRJ,
    module: "projects",
    description: "Aprovar orçamentos técnicos de projetos.",
    type: "action",
    parentKey: "projects.view",
    requires: ["projects.view"],
    risk: "sensitive",
  }),
  perm({
    key: "projects.convert",
    label: "Projetos — Converter em cadastro oficial",
    group: PRJ,
    module: "projects",
    description: "Converter projeto aprovado em produto, componente, BOM e roteiro oficiais (ação futura).",
    type: "action",
    parentKey: "projects.view",
    requires: ["projects.view", "projects.manage"],
    risk: "critical",
  }),

  // —— Manutenção ——
  perm({ key: "maintenance.view", label: "Manutenção", group: MNT, module: "maintenance", description: "Acessar manutenção predial.", type: "menu" }),
  perm({
    key: "maintenance.manage",
    label: "Manutenção — Gerenciar",
    group: MNT,
    module: "maintenance",
    description: "Gerenciar registros de manutenção.",
    type: "action",
    parentKey: "maintenance.view",
    requires: ["maintenance.view"],
  }),

  // —— Gestão de Frota (legado + granular; legado implica granular no backend) ——
  perm({
    key: "fleet.view",
    label: "Gestão de Frota — Acesso",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada: acesso ao módulo e visualização geral (sem valores financeiros).",
    type: "menu",
  }),
  perm({
    key: "fleet.dashboard.view",
    label: "Frota — Dashboard",
    group: FLT,
    module: "fleet",
    description: "Visualizar painel e indicadores operacionais da frota.",
    type: "section",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.reports.view",
    label: "Frota — Relatórios",
    group: FLT,
    module: "fleet",
    description: "Consultar relatórios operacionais da frota.",
    type: "section",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.vehicles.view",
    label: "Frota — Ver veículos",
    group: FLT,
    module: "fleet",
    description: "Listar e consultar fichas de veículos.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.vehicles.create",
    label: "Frota — Cadastrar veículos",
    group: FLT,
    module: "fleet",
    description: "Incluir novos veículos na frota.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view", "fleet.vehicles.view"],
  }),
  perm({
    key: "fleet.vehicles.edit",
    label: "Frota — Editar veículos",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada: cadastrar, editar veículos, contratos e documentos vinculados.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view", "fleet.vehicles.view"],
  }),
  perm({
    key: "fleet.vehicles.status.manage",
    label: "Frota — Status do veículo",
    group: FLT,
    module: "fleet",
    description: "Alterar status operacional, bloqueio e baixa de veículos.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view", "fleet.vehicles.view"],
    risk: "sensitive",
  }),
  perm({
    key: "fleet.contracts.view",
    label: "Frota — Ver contratos",
    group: FLT,
    module: "fleet",
    description: "Consultar contratos de locação e vínculos.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.contracts.manage",
    label: "Frota — Gerenciar contratos",
    group: FLT,
    module: "fleet",
    description: "Criar e alterar contratos de veículos.",
    type: "action",
    parentKey: "fleet.contracts.view",
    requires: ["fleet.view", "fleet.contracts.view"],
  }),
  perm({
    key: "fleet.documents.view",
    label: "Frota — Ver documentos",
    group: FLT,
    module: "fleet",
    description: "Consultar documentos e vencimentos dos veículos.",
    type: "action",
    parentKey: "fleet.vehicles.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.documents.manage",
    label: "Frota — Gerenciar documentos",
    group: FLT,
    module: "fleet",
    description: "Cadastrar e atualizar documentos da frota.",
    type: "action",
    parentKey: "fleet.documents.view",
    requires: ["fleet.view", "fleet.documents.view"],
  }),
  perm({
    key: "fleet.drivers.view",
    label: "Frota — Ver motoristas",
    group: FLT,
    module: "fleet",
    description: "Consultar cadastro de motoristas e CNH.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.drivers.manage",
    label: "Frota — Gerenciar motoristas",
    group: FLT,
    module: "fleet",
    description: "Cadastrar e editar motoristas.",
    type: "action",
    parentKey: "fleet.drivers.view",
    requires: ["fleet.view", "fleet.drivers.view"],
  }),
  perm({
    key: "fleet.reservations.view",
    label: "Frota — Ver reservas",
    group: FLT,
    module: "fleet",
    description: "Consultar agenda e reservas de veículos.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.reservations.create",
    label: "Frota — Criar reservas",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada: criar reservas e operar retirada/devolução (checkout/check-in).",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
  }),
  perm({
    key: "fleet.reservations.approve",
    label: "Frota — Aprovar reservas",
    group: FLT,
    module: "fleet",
    description: "Permissão legada: aprovar ou rejeitar solicitações de reserva.",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
    risk: "critical",
  }),
  perm({
    key: "fleet.reservations.manage",
    label: "Frota — Administrar reservas",
    group: FLT,
    module: "fleet",
    description: "Alterar reservas, substituir veículo e ações administrativas.",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
    risk: "sensitive",
  }),
  perm({
    key: "fleet.usage.checkout",
    label: "Frota — Retirada (checkout)",
    group: FLT,
    module: "fleet",
    description: "Registrar retirada do veículo e checklist de saída.",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
  }),
  perm({
    key: "fleet.usage.checkin",
    label: "Frota — Devolução (check-in)",
    group: FLT,
    module: "fleet",
    description: "Registrar devolução do veículo e checklist de retorno.",
    type: "action",
    parentKey: "fleet.reservations.view",
    requires: ["fleet.view", "fleet.reservations.view"],
  }),
  perm({
    key: "fleet.maintenance.view",
    label: "Frota — Ver manutenções",
    group: FLT,
    module: "fleet",
    description: "Consultar ordens e histórico de manutenção.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.maintenance.manage",
    label: "Frota — Gerenciar manutenções",
    group: FLT,
    module: "fleet",
    description: "Permissão legada: abrir, editar e encerrar manutenções.",
    type: "action",
    parentKey: "fleet.maintenance.view",
    requires: ["fleet.view", "fleet.maintenance.view"],
  }),
  perm({
    key: "fleet.costs.view",
    label: "Frota — Ver custos",
    group: FLT,
    module: "fleet",
    description: "Consultar lançamentos de custos (valores podem permanecer mascarados).",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
  }),
  perm({
    key: "fleet.costs.manage",
    label: "Frota — Lançar custos",
    group: FLT,
    module: "fleet",
    description: "Registrar e alterar custos operacionais da frota.",
    type: "action",
    parentKey: "fleet.costs.view",
    requires: ["fleet.view", "fleet.costs.view"],
    risk: "sensitive",
  }),
  perm({
    key: "fleet.financial.view",
    label: "Frota — Dados financeiros",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada: visualizar valores monetários, multas e indicadores financeiros.",
    type: "action",
    parentKey: "fleet.costs.view",
    requires: ["fleet.view", "fleet.costs.view"],
    risk: "critical",
  }),
  perm({
    key: "fleet.manage",
    label: "Frota — Administrador (legado)",
    group: FLT,
    module: "fleet",
    description:
      "Permissão legada ampla: quase todas as operações, exceto configurações (exige fleet.settings.manage).",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
    risk: "critical",
  }),
  perm({
    key: "fleet.settings.manage",
    label: "Frota — Configurações",
    group: FLT,
    module: "fleet",
    description: "Alterar parâmetros, importações e políticas do módulo de frota.",
    type: "action",
    parentKey: "fleet.view",
    requires: ["fleet.view"],
    risk: "critical",
  }),

  // —— Estoque / Almoxarifado ——
  perm({
    key: "inventory.view",
    label: "Estoque",
    group: INV,
    module: "inventory",
    description: "Acessar o módulo de estoque e consultar saldos, movimentações e dashboard.",
    type: "menu",
  }),
  perm({
    key: "inventory.manage",
    label: "Estoque — Gerenciar",
    group: INV,
    module: "inventory",
    description: "Cadastrar e editar itens, almoxarifados, conferências e ajustes (perfil gestor legado).",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.item.manage",
    label: "Estoque — Itens",
    group: INV,
    module: "inventory",
    description: "Cadastrar e editar itens de estoque.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.warehouse.manage",
    label: "Estoque — Almoxarifados",
    group: INV,
    module: "inventory",
    description: "Cadastrar e editar almoxarifados e locais.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.movements.create",
    label: "Estoque — Registrar movimentação",
    group: INV,
    module: "inventory",
    description: "Registrar movimentações manuais de estoque (entrada, saída, transferência).",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.movement.create",
    label: "Estoque — Movimentar",
    group: INV,
    module: "inventory",
    description: "Registrar entradas e saídas manuais.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.adjustment.create",
    label: "Estoque — Ajustes",
    group: INV,
    module: "inventory",
    description: "Registrar ajustes positivos e negativos de estoque.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
    risk: "high",
  }),
  perm({
    key: "inventory.transfer.create",
    label: "Estoque — Transferências",
    group: INV,
    module: "inventory",
    description: "Transferir itens entre almoxarifados.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.block.manage",
    label: "Estoque — Bloqueio",
    group: INV,
    module: "inventory",
    description: "Bloquear e desbloquear saldo de itens.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.movements.override",
    label: "Estoque — Override de saldo",
    group: INV,
    module: "inventory",
    description: "Permitir saída acima do saldo disponível (com auditoria).",
    type: "action",
    parentKey: "inventory.movements.create",
    requires: ["inventory.view", "inventory.movements.create"],
    risk: "critical",
  }),
  perm({
    key: "inventory.reservations.manage",
    label: "Estoque — Reservas",
    group: INV,
    module: "inventory",
    description: "Criar e cancelar reservas manuais de estoque.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.reservation.manage",
    label: "Estoque — Reservas (granular)",
    group: INV,
    module: "inventory",
    description: "Criar e cancelar reservas manuais.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.count.manage",
    label: "Estoque — Conferência física",
    group: INV,
    module: "inventory",
    description: "Abrir e contar sessões de inventário físico.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.count.approve",
    label: "Estoque — Aprovar conferência",
    group: INV,
    module: "inventory",
    description: "Aprovar conferências com divergência e liberar geração de ajustes.",
    type: "action",
    parentKey: "inventory.count.manage",
    requires: ["inventory.view", "inventory.count.manage"],
    risk: "high",
  }),
  perm({
    key: "inventory.audit.view",
    label: "Estoque — Auditoria",
    group: INV,
    module: "inventory",
    description: "Consultar trilha de auditoria detalhada do estoque.",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),
  perm({
    key: "inventory.export",
    label: "Estoque — Exportar",
    group: INV,
    module: "inventory",
    description: "Exportar saldos e movimentações (CSV/XLSX).",
    type: "action",
    parentKey: "inventory.view",
    requires: ["inventory.view"],
  }),

  // —— Comissões ——
  perm({
    key: "commissions.view",
    label: "Comissões",
    group: CM,
    module: "commissions",
    description: "Acesso ao módulo de comissões.",
    type: "menu",
  }),
  perm({
    key: "commissions.dashboard.view",
    label: "Comissões — Dashboard",
    group: CM,
    module: "commissions",
    description: "Dashboard executivo de comissões.",
    type: "section",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.forecast.view",
    label: "Comissões — Previstas",
    group: CM,
    module: "commissions",
    description: "Consultar comissões previstas (pedido de venda).",
    type: "tab",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.confirmed.view",
    label: "Comissões — Confirmadas",
    group: CM,
    module: "commissions",
    description: "Consultar comissões confirmadas por documento de saída.",
    type: "tab",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.release.view",
    label: "Comissões — Liberação",
    group: CM,
    module: "commissions",
    description: "Consultar liberação por recebimento.",
    type: "tab",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.release.manage",
    label: "Comissões — Gerenciar liberação",
    group: CM,
    module: "commissions",
    description: "Aprovar ou liberar comissões manualmente.",
    type: "action",
    parentKey: "commissions.release.view",
    requires: ["commissions.view", "commissions.release.view"],
  }),
  perm({
    key: "commissions.payments.view",
    label: "Comissões — Pagamentos",
    group: CM,
    module: "commissions",
    description: "Consultar lotes e pagamentos de comissão.",
    type: "tab",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.payments.manage",
    label: "Comissões — Registrar pagamentos",
    group: CM,
    module: "commissions",
    description: "Criar, aprovar e registrar pagamentos de comissão.",
    type: "action",
    parentKey: "commissions.payments.view",
    requires: ["commissions.view", "commissions.payments.view"],
    risk: "high",
  }),
  perm({
    key: "commissions.people.view",
    label: "Comissões — Pessoas",
    group: CM,
    module: "commissions",
    description: "Consultar pessoas comissionadas.",
    type: "tab",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.people.manage",
    label: "Comissões — CRUD pessoas",
    group: CM,
    module: "commissions",
    description: "Cadastrar e editar pessoas comissionadas.",
    type: "action",
    parentKey: "commissions.people.view",
    requires: ["commissions.view", "commissions.people.view"],
  }),
  perm({
    key: "commissions.rules.view",
    label: "Comissões — Regras",
    group: CM,
    module: "commissions",
    description: "Consultar regras de comissão.",
    type: "tab",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.rules.manage",
    label: "Comissões — CRUD regras",
    group: CM,
    module: "commissions",
    description: "Cadastrar e editar regras de comissão.",
    type: "action",
    parentKey: "commissions.rules.view",
    requires: ["commissions.view", "commissions.rules.view"],
    risk: "high",
  }),
  perm({
    key: "commissions.audit.view",
    label: "Comissões — Auditoria",
    group: CM,
    module: "commissions",
    description: "Consultar divergências e issues de auditoria.",
    type: "tab",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.settings.view",
    label: "Comissões — Configurações",
    group: CM,
    module: "commissions",
    description: "Consultar parâmetros globais do módulo de comissões.",
    type: "tab",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.seller.all",
    label: "Comissões — Todos os vendedores",
    group: CM,
    module: "commissions",
    description: "Visualizar comissões de todos os vendedores (gestor).",
    type: "action",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
  perm({
    key: "commissions.seller.own",
    label: "Comissões — Próprias comissões",
    group: CM,
    module: "commissions",
    description: "Visualizar apenas comissões do vendedor vinculado ao usuário.",
    type: "action",
    parentKey: "commissions.view",
    requires: ["commissions.view"],
  }),
];

export const ALL_PERMISSION_KEYS = PERMISSION_CATALOG.map((p) => p.key);

export const PERMISSION_GROUP_ORDER = [
  G,
  CRM,
  CLI,
  PROP,
  SO,
  ENG,
  COMP,
  PRC,
  OPS,
  SYS,
  MNT,
  FLT,
  INV,
  CM,
] as const;
