/**
 * Helpers puros: congelamento de custo da Engenharia de Produto → tabela versionada.
 */
import { toCivilDateKey } from "./financeCivilDate.js";
import type { OfficialProductFinalCostSuccess } from "./productOfficialFinalCost.js";
import { resolveProductEngineeringCostWarning } from "./productEngineeringCostWarning.js";

export const PRODUCTION_COST_ENGINEERING_SNAPSHOT_SOURCE = "PRODUCT_ENGINEERING_CHANGE" as const;

/** Tipos de item da Engenharia elegíveis para a tabela oficial de custo de produção. */
export const PRODUCTION_COST_TABLE_ELIGIBLE_ITEM_TYPES = ["PRODUCT", "COMPONENT"] as const;

export type ProductionCostTableEligibleItemType =
  (typeof PRODUCTION_COST_TABLE_ELIGIBLE_ITEM_TYPES)[number];

export function isProductionCostTableEligibleItemType(
  type: string
): type is ProductionCostTableEligibleItemType {
  return type === "PRODUCT" || type === "COMPONENT";
}

export function productionCostTableEligibleItemTypesFilter(): {
  in: ProductionCostTableEligibleItemType[];
} {
  return { in: [...PRODUCTION_COST_TABLE_ELIGIBLE_ITEM_TYPES] };
}

export type FrozenCostTraceStatus =
  | "ATUALIZADO"
  | "PENDENTE_PUBLICACAO"
  | "SEM_CUSTO_CONGELADO"
  | "CUSTO_DIVERGENTE"
  | "SNAPSHOT_TECNICO_SEM_IMPACTO"
  | "SEM_CUSTO";

export type ProductEngineeringCostSnapshotConfig = {
  autoGenerateDraft: boolean;
  autoPublishEngineeringCostSnapshots: boolean;
};

export function readProductEngineeringCostSnapshotConfig(): ProductEngineeringCostSnapshotConfig {
  const autoPublish =
    process.env.AUTO_PUBLISH_ENGINEERING_COST_SNAPSHOTS === "true" ||
    process.env.AUTO_PUBLISH_ENGINEERING_COST_SNAPSHOTS === "1";
  const autoGenerateDraft =
    process.env.AUTO_GENERATE_ENGINEERING_COST_DRAFT === "false" ||
    process.env.AUTO_GENERATE_ENGINEERING_COST_DRAFT === "0"
      ? false
      : true;
  return {
    autoGenerateDraft,
    autoPublishEngineeringCostSnapshots: autoPublish,
  };
}

function readAnalysisRecord(analysis: unknown): Record<string, unknown> {
  if (!analysis || typeof analysis !== "object") return {};
  return analysis as Record<string, unknown>;
}

/** Custo zero só é aceito quando o motor indica explicitamente custo real zero. */
export function isExplicitlyValidZeroProductionCost(
  resolved: OfficialProductFinalCostSuccess,
  analysis: unknown
): boolean {
  if (resolved.finalUnitCost !== 0) return false;
  const raw = readAnalysisRecord(analysis);
  if (raw.explicitZeroCost === true) return true;
  const summary =
    raw.summary && typeof raw.summary === "object"
      ? (raw.summary as Record<string, unknown>)
      : raw;
  const costingMode = raw.costingMode ?? summary.costingMode;
  if (costingMode !== "BOM_ONLY") return false;
  const material = resolved.breakdown.totalMaterialCost ?? 0;
  const hh = resolved.breakdown.totalHH_Unit ?? 0;
  const hm = resolved.breakdown.totalHM_Unit ?? 0;
  return material === 0 && hh === 0 && hm === 0 && !resolved.costAnalysisPartial;
}

export function isCalculableProductionUnitCost(
  resolved: OfficialProductFinalCostSuccess,
  analysis: unknown
): boolean {
  if (resolved.finalUnitCost > 0) return true;
  return (
    resolved.finalUnitCost === 0 && isExplicitlyValidZeroProductionCost(resolved, analysis)
  );
}

export function incrementalProductionCostVersionCode(
  effectiveDate: Date,
  productCode: string
): string {
  const dateKey = toCivilDateKey(effectiveDate) ?? "unknown";
  const safeCode = productCode.trim().replace(/\s+/g, "-");
  return `AUTO-${dateKey}-${safeCode}`;
}

export function incrementalProductionCostVersionName(productCode: string): string {
  return `Atualização automática de custo — ${productCode.trim()}`;
}

export function resolveFrozenCostTraceStatus(input: {
  liveCiu: number | null;
  liveHash: string | null;
  publishedCost: number | null;
  publishedHash: string | null;
  publishedVersionStatus: string | null;
  draftHash: string | null;
  draftVersionStatus: string | null;
  draftUnitCost?: number | null;
}): FrozenCostTraceStatus {
  if (input.liveCiu == null) return "SEM_CUSTO";

  const hasPublished =
    input.publishedVersionStatus === "PUBLISHED" &&
    input.publishedCost != null &&
    input.publishedCost > 0;

  const hasDraft = input.draftVersionStatus === "DRAFT" && input.draftHash != null;

  if (!hasPublished && !hasDraft) return "SEM_CUSTO_CONGELADO";

  const calculatedCost =
    hasDraft && input.draftUnitCost != null && input.draftUnitCost > 0
      ? input.draftUnitCost
      : input.liveCiu;
  const calculatedHash = hasDraft ? input.draftHash : input.liveHash;

  const warning = resolveProductEngineeringCostWarning({
    officialCost: hasPublished ? input.publishedCost : null,
    calculatedCost,
    officialHash: input.publishedHash,
    calculatedHash,
    hasDraft,
    hasOfficialPublished: hasPublished,
  });

  switch (warning.warningStatus) {
    case "COST_DIFF_PENDING_PUBLICATION":
      return hasDraft ? "PENDENTE_PUBLICACAO" : "CUSTO_DIVERGENTE";
    case "TECHNICAL_SNAPSHOT_PENDING_NO_COST_IMPACT":
      return "SNAPSHOT_TECNICO_SEM_IMPACTO";
    case "MISSING_OFFICIAL_COST":
      return hasDraft ? "PENDENTE_PUBLICACAO" : "SEM_CUSTO_CONGELADO";
    case "COST_PUBLISHED_OK":
    case "NONE":
      return "ATUALIZADO";
    default:
      return "SEM_CUSTO_CONGELADO";
  }
}

export function frozenCostTraceStatusLabel(status: FrozenCostTraceStatus): string {
  switch (status) {
    case "ATUALIZADO":
      return "Atualizado";
    case "PENDENTE_PUBLICACAO":
      return "Pendente de publicação";
    case "SEM_CUSTO_CONGELADO":
      return "Sem custo congelado";
    case "CUSTO_DIVERGENTE":
      return "Custo divergente";
    case "SNAPSHOT_TECNICO_SEM_IMPACTO":
      return "Snapshot técnico pendente";
    case "SEM_CUSTO":
      return "Sem custo";
    default:
      return status;
  }
}
