/**
 * Helpers puros: congelamento de custo da Engenharia de Produto → tabela versionada.
 */
import { toCivilDateKey } from "./financeCivilDate.js";
import type { OfficialProductFinalCostSuccess } from "./productOfficialFinalCost.js";

export const PRODUCTION_COST_ENGINEERING_SNAPSHOT_SOURCE = "PRODUCT_ENGINEERING_CHANGE" as const;

export type FrozenCostTraceStatus =
  | "ATUALIZADO"
  | "PENDENTE_PUBLICACAO"
  | "SEM_CUSTO_CONGELADO"
  | "CUSTO_DIVERGENTE"
  | "SEM_CUSTO";

export type ProductEngineeringCostSnapshotConfig = {
  autoGenerateDraft: boolean;
  autoPublishEngineeringCostSnapshots: boolean;
};

export function readProductEngineeringCostSnapshotConfig(): ProductEngineeringCostSnapshotConfig {
  const autoPublish =
    process.env.AUTO_PUBLISH_ENGINEERING_COST_SNAPSHOTS === "true" ||
    process.env.AUTO_PUBLISH_ENGINEERING_COST_SNAPSHOTS === "1";
  const autoGenerateDraft =
    process.env.AUTO_GENERATE_ENGINEERING_COST_DRAFT === "false" ||
    process.env.AUTO_GENERATE_ENGINEERING_COST_DRAFT === "0"
      ? false
      : true;
  return {
    autoGenerateDraft,
    autoPublishEngineeringCostSnapshots: autoPublish,
  };
}

function readAnalysisRecord(analysis: unknown): Record<string, unknown> {
  if (!analysis || typeof analysis !== "object") return {};
  return analysis as Record<string, unknown>;
}

/** Custo zero só é aceito quando o motor indica explicitamente custo real zero. */
export function isExplicitlyValidZeroProductionCost(
  resolved: OfficialProductFinalCostSuccess,
  analysis: unknown
): boolean {
  if (resolved.finalUnitCost !== 0) return false;
  const raw = readAnalysisRecord(analysis);
  if (raw.explicitZeroCost === true) return true;
  const summary =
    raw.summary && typeof raw.summary === "object"
      ? (raw.summary as Record<string, unknown>)
      : raw;
  const costingMode = raw.costingMode ?? summary.costingMode;
  if (costingMode !== "BOM_ONLY") return false;
  const material = resolved.breakdown.totalMaterialCost ?? 0;
  const hh = resolved.breakdown.totalHH_Unit ?? 0;
  const hm = resolved.breakdown.totalHM_Unit ?? 0;
  return material === 0 && hh === 0 && hm === 0 && !resolved.costAnalysisPartial;
}

export function isCalculableProductionUnitCost(
  resolved: OfficialProductFinalCostSuccess,
  analysis: unknown
): boolean {
  if (resolved.finalUnitCost > 0) return true;
  return (
    resolved.finalUnitCost === 0 && isExplicitlyValidZeroProductionCost(resolved, analysis)
  );
}

export function incrementalProductionCostVersionCode(
  effectiveDate: Date,
  productCode: string
): string {
  const dateKey = toCivilDateKey(effectiveDate) ?? "unknown";
  const safeCode = productCode.trim().replace(/\s+/g, "-");
  return `AUTO-${dateKey}-${safeCode}`;
}

export function incrementalProductionCostVersionName(productCode: string): string {
  return `Atualização automática de custo — ${productCode.trim()}`;
}

export function resolveFrozenCostTraceStatus(input: {
  liveCiu: number | null;
  liveHash: string | null;
  publishedCost: number | null;
  publishedHash: string | null;
  publishedVersionStatus: string | null;
  draftHash: string | null;
  draftVersionStatus: string | null;
}): FrozenCostTraceStatus {
  if (input.liveCiu == null) return "SEM_CUSTO";

  const hasPublished =
    input.publishedHash != null &&
    input.publishedVersionStatus === "PUBLISHED" &&
    input.publishedCost != null &&
    input.publishedCost > 0;

  const hasDraft = input.draftHash != null && input.draftVersionStatus === "DRAFT";

  if (!hasPublished && !hasDraft) return "SEM_CUSTO_CONGELADO";

  if (hasPublished && input.liveHash && input.publishedHash === input.liveHash) {
    return "ATUALIZADO";
  }

  if (hasDraft && input.liveHash && input.draftHash === input.liveHash && !hasPublished) {
    return "PENDENTE_PUBLICACAO";
  }

  if (hasPublished && input.liveHash && input.publishedHash !== input.liveHash) {
    return "CUSTO_DIVERGENTE";
  }

  if (hasDraft && input.liveHash && input.draftHash !== input.liveHash) {
    return "CUSTO_DIVERGENTE";
  }

  if (hasDraft) return "PENDENTE_PUBLICACAO";

  return "SEM_CUSTO_CONGELADO";
}

export function frozenCostTraceStatusLabel(status: FrozenCostTraceStatus): string {
  switch (status) {
    case "ATUALIZADO":
      return "Atualizado";
    case "PENDENTE_PUBLICACAO":
      return "Pendente de publicação";
    case "SEM_CUSTO_CONGELADO":
      return "Sem custo congelado";
    case "CUSTO_DIVERGENTE":
      return "Custo divergente";
    case "SEM_CUSTO":
      return "Sem custo";
    default:
      return status;
  }
}
