import type { SystemGuideEntry } from "@/src/lib/systemGuide/types";

/** Artigos adicionais por âncora de seção — mesclados em index.ts */
export const SYSTEM_GUIDE_SECTION_EXTENSIONS: Record<string, SystemGuideEntry[]> = {
  dashboard: [
    {
      anchor: "dashboard-visao-executiva",
      title: "Visão Executiva — pedidos e faturamento",
      objective:
        "Interpretar indicadores de pedidos emitidos e faturamento de mercado com metas e projeções.",
      badge: "operacional",
      whoUses: "Diretoria, gestão comercial e financeira.",
      whereToAccess: "Menu lateral > Dashboard > aba Visão Executiva.",
      permissions: "Acesso ao módulo Dashboard.",
      features: [
        "Filtro de ano na visão executiva.",
        "Subaba Pedidos: evolução mensal, meta do mês, projeção anual e status dos pedidos.",
        "Subaba Faturamento: realizado vs projetado vs meta, média por dia útil e projeção de mês/ano.",
        "Indicadores administrativos e painéis de meta acumulada.",
      ],
      basicFlow: [
        "Abra Dashboard e selecione Visão Executiva.",
        "Escolha o ano no filtro superior.",
        "Alterne entre Pedidos e Faturamento conforme a análise desejada.",
        "Em Pedidos, compare realizado, meta e projeção; revise status dos pedidos.",
        "Em Faturamento, leia realizado vs projetado vs meta e as projeções de mês/ano.",
        "Use o atalho Ver pedidos quando precisar detalhar um indicador.",
      ],
      importantFields: [
        "Ano selecionado",
        "Pedidos emitidos",
        "Carteira aberta",
        "Faturamento realizado",
        "Meta",
        "Projeção",
      ],
      businessRules: [
        "Pedidos emitidos e faturamento são leituras distintas — não confunda volume de pedido com NF processada.",
        "Carteira aberta representa pedidos ainda não totalmente faturados/encerrados.",
        "Projeção usa média de dias úteis do ano até a data — meses futuros sem fechamento podem distorcer leitura.",
        "Metas exibidas seguem parâmetros configurados para o painel executivo.",
      ],
      commonErrors: [
        "Comparar projeção de dezembro em janeiro como se fosse valor fechado.",
        "Tratar carteira aberta como faturamento já realizado.",
        "Ignorar o ano selecionado ao apresentar gráficos em reunião.",
      ],
      examples: [
        "Reunião mensal: aba Pedidos para volume emitido; subaba Faturamento para receita de mercado.",
        "Análise de meta anual: comparar linha de realizado com projeção e meta acumulada.",
      ],
      securityNotes: ["Indicadores executivos são confidenciais — compartilhe só com público autorizado."],
      notes: [
        "Se uma subaba aparecer como indisponível, a tela informa o motivo — não force interpretação sem dados.",
        "Meses sem fechamento completo exigem cautela na leitura de projeção.",
      ],
      relatedModules: ["Pedidos de venda", "Propostas", "Relatórios"],
      relatedAnchors: ["comercial-propostas-pedidos-clientes", "indicadores-relatorios"],
      tags: ["pedidos", "faturamento", "meta", "projeção", "carteira"],
      alerts: [
        {
          type: "attention",
          text: "Projeção é estimativa baseada em dias úteis decorridos — não substitui fechamento contábil.",
        },
        {
          type: "tip",
          text: "Carteira aberta ≠ faturamento: carteira é pipeline operacional de pedidos ainda em curso.",
        },
      ],
    },
    {
      anchor: "dashboard-funil-vendas",
      title: "Funil de Vendas e pipeline de pedidos",
      objective: "Acompanhar pipeline comercial operacional com foco em pedidos de venda.",
      badge: "operacional",
      whoUses: "Gestão comercial e coordenação de vendas.",
      whereToAccess: "Menu lateral > Dashboard > aba Funil de Vendas.",
      permissions: "Acesso ao módulo Dashboard.",
      features: [
        "Pipeline operacional de pedidos (visão não linear).",
        "Pedidos emitidos, carteira, faturamento e pendências comerciais.",
        "Top clientes em carteira no ano.",
        "Percentual de pedidos do mês com NF processada.",
      ],
      basicFlow: [
        "Abra Dashboard > Funil de Vendas.",
        "Leia os cards de pipeline e carteira.",
        "Identifique atrasados e pendências.",
        "Use Ver pedidos para detalhar casos específicos.",
      ],
      importantFields: ["Carteira", "Emitidos", "Faturamento", "Atrasados", "Cliente"],
      businessRules: [
        "Etapas do funil podem se sobrepor (ex.: atrasados podem estar na carteira).",
        "Fonte principal: pedidos de venda cadastrados no IndusCost.",
      ],
      commonErrors: ["Tratar funil como sequência rígida única sem sobreposição de etapas."],
      examples: ["Reunião semanal de carteira usando top clientes e pedidos atrasados."],
      securityNotes: [],
      notes: ["Complementa a Visão Executiva com leitura operacional do pipeline."],
      relatedModules: ["Pedidos de venda", "Propostas", "CRM Comercial"],
      tags: ["funil", "pipeline", "carteira"],
      alerts: [],
    },
  ],
  financeiro: [
    {
      anchor: "financeiro-contas-receber",
      title: "Contas a Receber",
      objective: "Acompanhar títulos a receber sincronizados do Nomus com filtros e indicadores.",
      badge: "financeiro",
      whoUses: "Financeiro, cobrança e controladoria.",
      whereToAccess: "Menu lateral > Financeiro > Contas a Receber.",
      permissions: "Perfil com acesso a contas a receber no módulo Financeiro.",
      features: [
        "Abas: Visão Geral, Aging, Agenda, Clientes, Títulos, Formas de Pagamento, Empresas.",
        "Filtros por ano, mês e status — afetam KPIs, gráficos e listas.",
        "Cards de indicadores na visão geral.",
        "Dados originados da sincronização Nomus.",
      ],
      basicFlow: [
        "Abra Financeiro > Contas a Receber.",
        "Ajuste filtros de ano/mês/status conforme o recorte desejado.",
        "Na Visão Geral, leia os cards de aberto, recebido/liquidado e vencido.",
        "Use Aging para faixas de vencimento.",
        "Use Títulos ou Clientes para detalhar casos.",
        "Se valores parecerem desatualizados, confira última sincronização Nomus em Configurações.",
      ],
      importantFields: ["Cliente", "Vencimento", "Valor em aberto", "Status", "Empresa"],
      businessRules: [
        "Títulos exibidos dependem da sincronização Nomus.",
        "Filtros ativos alteram todos os painéis da tela simultaneamente.",
        "Aberto, recebido/liquidado e vencido têm significados distintos — não misture na análise.",
      ],
      commonErrors: [
        "Analisar KPIs sem perceber filtro de mês/ano ativo.",
        "Cobrar cliente com base em título já liquidado na última sync.",
      ],
      examples: ["Reunião de cobrança: aba Aging + filtro do mês corrente."],
      securityNotes: ["Dados de clientes e valores são sensíveis."],
      notes: ["Exportação pode estar disponível conforme evolução da tela — valide botões visíveis."],
      relatedModules: ["Integração Nomus", "Configurações"],
      relatedAnchors: ["integracao-nomus", "configuracoes-hub-central"],
      tags: ["contas-a-receber", "aging", "cobrança"],
      alerts: [
        { type: "tip", text: "Sempre confira a data da última sincronização Nomus antes de fechar análise." },
      ],
    },
    {
      anchor: "financeiro-contas-pagar",
      title: "Contas a Pagar",
      objective: "Acompanhar obrigações com fornecedores sincronizadas do Nomus.",
      badge: "financeiro",
      whoUses: "Financeiro, contas a pagar e tesouraria.",
      whereToAccess: "Menu lateral > Financeiro > Contas a Pagar.",
      permissions: "Perfil com acesso a contas a pagar no módulo Financeiro.",
      features: [
        "Abas: Visão Geral, Aging, Agenda de Pagamentos, Fornecedores, Títulos, Formas de Pagamento, Empresas.",
        "Filtros por ano, mês e status.",
        "Cards e gráficos na visão geral.",
        "Exportação para CSV quando o botão estiver disponível na tela.",
        "Dados sincronizados do Nomus.",
      ],
      basicFlow: [
        "Abra Financeiro > Contas a Pagar.",
        "Defina filtros de período e status.",
        "Leia KPIs de aberto vs pago na Visão Geral.",
        "Use Agenda de Pagamentos para vencimentos próximos.",
        "Detalhe fornecedor ou título nas abas específicas.",
        "Exporte CSV se necessário para análise externa autorizada.",
      ],
      importantFields: ["Fornecedor", "Vencimento", "Valor", "Status", "Empresa"],
      businessRules: [
        "Aberto e pago são status distintos na leitura financeira.",
        "Filtros impactam KPIs, gráficos, exportação e listagem de títulos.",
      ],
      commonErrors: [
        "Programar pagamento sem revisar status já liquidado na sync.",
        "Exportar CSV com filtros incorretos e tomar decisão errada.",
      ],
      examples: ["Agenda semanal: aba Agenda de Pagamentos com filtro da semana."],
      securityNotes: ["Fornecedores e valores não devem ser compartilhados externamente."],
      notes: [],
      relatedModules: ["Integração Nomus", "Configurações"],
      relatedAnchors: ["integracao-nomus", "configuracoes-hub-central"],
      tags: ["contas-a-pagar", "fornecedores", "exportação"],
      alerts: [],
    },
  ],
  "gestao-frota": [
    {
      anchor: "frota-veiculos",
      title: "Veículos — cadastro e ficha",
      objective: "Manter frota cadastrada com status visual e QR de checklist por veículo.",
      badge: "frota",
      whoUses: "Gestão de frota e administrativo.",
      whereToAccess: "Gestão de Frota > Veículos.",
      permissions: "Visualização para operação; edição conforme perfil de frota.",
      features: [
        "Lista com placa, modelo, origem, status e quilometragem.",
        "Filtros por status e origem.",
        "Ficha do veículo: documentos, contratos, histórico, manutenções, usos e QR de checklist.",
        "Status operacional: Disponível, Reservado, Em uso, Manutenção, Bloqueado, etc.",
      ],
      basicFlow: [
        "Abra Veículos e use filtros se necessário.",
        "Clique para abrir a ficha do veículo.",
        "Revise status e documentos antes de liberar reserva.",
        "Na ficha, gere ou copie o QR fixo de checklist do veículo.",
      ],
      importantFields: ["Placa", "Status", "Km atual", "Unidade", "Origem do veículo"],
      businessRules: [
        "Veículo em Manutenção ou Bloqueado não deve ser reservado.",
        "Documentos vencidos podem bloquear reserva conforme parâmetros da frota.",
        "QR de checklist é fixo por veículo — imprima e fixe no carro.",
      ],
      commonErrors: [
        "Reservar veículo indisponível sem checar status na lista.",
        "Não regenerar QR após vazamento do link antigo.",
      ],
      examples: ["Novo veículo: cadastrar, ativar QR de checklist, colar QR no para-brisa."],
      securityNotes: ["QR do veículo permite check-in/out — controle quem tem acesso físico ao QR."],
      notes: ["Contratos e documentos ficam na ficha, não em menu separado."],
      relatedModules: ["Checklists", "Reservas", "Configurações"],
      relatedAnchors: ["frota-checklist-qr", "frota-reserva-qr-publico"],
      tags: ["veículos", "status", "qr"],
      alerts: [],
    },
    {
      anchor: "frota-motoristas",
      title: "Motoristas e CNH",
      objective: "Cadastrar condutores, acompanhar CNH e aprovar motoristas vindos do QR público.",
      badge: "frota",
      whoUses: "Gestão de frota e RH administrativo.",
      whereToAccess: "Gestão de Frota > Motoristas.",
      permissions: "Gestão de motoristas conforme perfil de frota.",
      features: [
        "Lista com nome, CPF, status, validade da CNH e alertas.",
        "Filtros por status, unidade, CNH vencida/vencendo.",
        "Cadastro e edição de motoristas autorizados.",
        "Aprovação de motorista criado via solicitação pública.",
      ],
      basicFlow: [
        "Abra Motoristas.",
        "Filtre CNH vencida ou vencendo para ações preventivas.",
        "Cadastre ou edite motorista com dados de CNH completos.",
        "Aprove motoristas pendentes vindos de Solicitações QR.",
      ],
      importantFields: ["Nome", "CPF", "Categoria CNH", "Validade CNH", "Status"],
      businessRules: [
        "CNH vencida pode bloquear retirada conforme parâmetros.",
        "Motorista Pendente ou Bloqueado não deve conduzir até regularização.",
      ],
      commonErrors: ["Aprovar motorista sem validar CNH.", "Ignorar alertas de vencimento na lista."],
      examples: ["Mensal: filtrar CNH vencendo nos próximos 30 dias."],
      securityNotes: ["CPF e dados de CNH são dados pessoais — acesso restrito."],
      notes: [],
      relatedModules: ["Solicitações QR", "Reservas"],
      tags: ["motoristas", "cnh"],
      alerts: [
        { type: "permission", text: "Aprovação de motorista público exige perfil com permissão de aprovação de reservas." },
      ],
    },
    {
      anchor: "frota-reservas-internas",
      title: "Reservas — agenda e aprovação",
      objective: "Gerir reservas internas com agenda, aprovação, retirada e devolução.",
      badge: "frota",
      whoUses: "Gestão de frota e solicitantes internos autorizados.",
      whereToAccess: "Gestão de Frota > Reservas.",
      permissions: "Criar, aprovar ou gerenciar reservas conforme perfil.",
      features: [
        "Visão em lista ou semana.",
        "Filtros por data, veículo, motorista e status.",
        "Criação de reserva interna.",
        "Aprovação, rejeição e cancelamento com motivo.",
        "Retirada e devolução (check-in/check-out interno).",
        "Indicador de checklist por reserva.",
      ],
      basicFlow: [
        "Abra Reservas.",
        "Filtre por período ou status pendente.",
        "Crie nova reserva ou aprove solicitação já convertida.",
        "Na data, registre retirada e devolução pelo fluxo da reserva.",
        "Acompanhe status do checklist na linha da reserva.",
      ],
      importantFields: ["Veículo", "Motorista", "Início/fim", "Destino", "Status da reserva"],
      businessRules: [
        "Status claros: solicitada, aguardando aprovação, aprovada, em uso, finalizada, cancelada, etc.",
        "Reserva aprovada aguarda check-in na janela da reserva.",
        "Em uso aguarda check-out ao devolver.",
      ],
      commonErrors: [
        "Aprovar sem veículo disponível no período.",
        "Esquecer check-out e deixar veículo como em uso.",
      ],
      examples: ["Reserva corporativa: criar, aprovar, motorista faz check-in pelo QR do veículo."],
      securityNotes: [],
      notes: ["Uso em campo também disponível em Gestão de Frota > rota dedicada /fleet/field."],
      relatedModules: ["Checklists", "Solicitações QR"],
      tags: ["reservas", "agenda", "aprovação"],
      alerts: [],
    },
    {
      anchor: "frota-configuracoes",
      title: "Configurações da Frota",
      objective: "Configurar link público de reserva, parâmetros operacionais e ferramentas admin.",
      badge: "administrativo",
      whoUses: "Administrador de frota e super administrador.",
      whereToAccess: "Gestão de Frota > Configurações.",
      permissions: "Parâmetros: perfil de configuração da frota; limpeza: super administrador.",
      features: [
        "Painel de link/QR público de reserva (copiar, ativar, regenerar).",
        "Parâmetros: bloqueio por documento/CNH, checklist obrigatório, reserva pública habilitada.",
        "Importação CSV de veículos e motoristas (perfil de gestão).",
        "Limpeza administrativa de reservas de teste (somente super admin).",
      ],
      basicFlow: [
        "Abra Configurações da Frota.",
        "Copie o link curto ou técnico de reserva pública e compartilhe com critério.",
        "Ajuste parâmetros operacionais e salve.",
        "Use importação CSV apenas com arquivo validado em preview.",
        "Limpeza de testes: só super admin, com frase de confirmação.",
      ],
      importantFields: ["URL base pública", "Token de reserva", "Parâmetros sim/não"],
      businessRules: [
        "Regenerar token invalida links/QR antigos de reserva.",
        "Limpeza apaga reservas, solicitações, checklists e logs — irreversível.",
        "QR de checklist é por veículo (na ficha), não nesta tela.",
      ],
      commonErrors: [
        "Divulgar link público sem aprovação interna estruturada.",
        "Rodar limpeza em produção sem ambiente de teste.",
      ],
      examples: ["Ativar reserva pública, copiar link curto, colar em comunicado interno."],
      securityNotes: [
        "Token e links públicos são sensíveis.",
        "Limpeza administrativa é destrutiva — uso restrito a super administrador.",
      ],
      notes: [],
      relatedModules: ["Solicitações QR", "Veículos"],
      relatedAnchors: ["frota-reserva-qr-publico"],
      tags: ["configuração", "qr", "token"],
      statusNote: "Limpeza administrativa: uso restrito (super admin).",
      alerts: [
        { type: "attention", text: "Não regenere o token público sem avisar usuários que já têm o link antigo." },
      ],
    },
  ],
  "frota-reserva-publica": [
    {
      anchor: "frota-reserva-multiplos-periodos",
      title: "Seleção de vários períodos no mesmo dia",
      objective: "Permitir ao solicitante público escolher slots contíguos no mesmo dia em uma única solicitação.",
      badge: "frota",
      whoUses: "Solicitantes externos e gestão que aprova.",
      whereToAccess: "Formulário público de reserva (link/QR) > seleção de horários.",
      permissions: "Canal público habilitado em Configurações da Frota.",
      features: [
        "Grade de slots por dia.",
        "Seleção de múltiplos horários contíguos no mesmo dia.",
        "Consolidação em um único período (início/fim) na solicitação.",
      ],
      basicFlow: [
        "No formulário público, escolha o dia.",
        "Selecione um ou mais slots disponíveis em sequência.",
        "Confirme o período consolidado exibido.",
        "Envie a solicitação para aprovação interna.",
      ],
      importantFields: ["Dia", "Slots selecionados", "Período consolidado"],
      businessRules: [
        "Slots devem estar disponíveis e contíguos conforme regras da tela.",
        "Uma solicitação representa um único período consolidado.",
      ],
      commonErrors: ["Selecionar slots não contíguos quando a tela exige sequência."],
      examples: ["Reserva das 8h às 12h selecionando quatro slots de 1h no mesmo dia."],
      securityNotes: [],
      notes: [],
      relatedModules: ["Solicitações QR"],
      tags: ["multi-slot", "reserva pública"],
      alerts: [],
    },
  ],
  "frota-checklist-qr": [
    {
      anchor: "frota-checklist-detalhes",
      title: "Checklist QR — itens, odômetro e auto check-out",
      objective: "Detalhar o fluxo completo do checklist fixo por veículo.",
      badge: "frota",
      whoUses: "Motoristas e gestão de frota.",
      whereToAccess:
        "QR fixo no veículo (público); geração do QR em Veículos > ficha > painel QR; histórico em Checklists.",
      permissions: "Checklist público exige reserva válida e CPF do motorista.",
      features: [
        "Itens padronizados (lataria, pneus, documentos, limpeza, etc.) com OK, Atenção, Avaria ou Não se aplica.",
        "Odômetro e nível de combustível obrigatórios.",
        "Observações gerais e aceite de responsabilidade.",
        "Identificação automática da reserva pelo CPF na janela do período.",
        "Check-in (retirada) e check-out (devolução).",
        "Auto check-out quando novo check-in ocorre sem devolução anterior (auditoria).",
        "Histórico por veículo, reserva e aba Checklists (pendentes, realizados, atenções).",
      ],
      basicFlow: [
        "Gestor gera QR na ficha do veículo e fixa no carro.",
        "Motorista escaneia QR, informa CPF e confirma reserva sugerida.",
        "Preenche itens, odômetro, combustível e envia check-in.",
        "Na devolução, repete processo para check-out.",
        "Gestor revisa atenções/avarias em Checklists.",
      ],
      importantFields: ["CPF", "Odômetro", "Combustível", "Itens do checklist", "Tipo check-in/out"],
      businessRules: [
        "Check-in só na janela da reserva aprovada.",
        "Check-out após check-in, dentro da janela estendida.",
        "Auto check-out registra devolução presumida para liberar próximo uso — fica auditado.",
      ],
      commonErrors: [
        "Motorista tentar checklist sem reserva ativa no período.",
        "Omitir itens com avaria na devolução.",
      ],
      examples: ["Devolução com arranhão marcado como Avaria no item Lataria lateral."],
      securityNotes: ["Não compartilhar QR com pessoas sem reserva autorizada."],
      notes: ["Fotos no checklist podem estar em implantação futura — use observações textuais."],
      relatedModules: ["Reservas", "Veículos"],
      tags: ["checklist", "odômetro", "auto-checkout"],
      alerts: [
        { type: "tip", text: "Imprima o QR em tamanho legível e proteja contra intempéries no veículo." },
      ],
    },
  ],
};
