-- Central de Tesouraria — tipos do motor determinístico de exceções.
-- Aditiva: ALTER TYPE ADD VALUE (sem DROP). Não aplicar em produção via Cursor.

ALTER TYPE "TreasuryExceptionType" ADD VALUE 'EXPECTED_RECEIPT_NOT_RECEIVED';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'EXPECTED_PAYMENT_NOT_MADE';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'OVERDUE_RECEIVABLE_WITHOUT_ACTION';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'EXPIRED_PROMISE';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'CRITICAL_PAYMENT_NOT_PROGRAMMED';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'ACCOUNT_BELOW_MINIMUM';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'ACCOUNT_PROJECTION_NEGATIVE';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'CONSOLIDATED_PROJECTION_NEGATIVE';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'STALE_BALANCE';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'BANK_MOVEMENT_UNIDENTIFIED';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'RECONCILIATION_DIFFERENCE';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'TITLE_WITHOUT_RESPONSIBLE';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'SYNC_DELAYED';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'SUSPECTED_DUPLICATE';
ALTER TYPE "TreasuryExceptionType" ADD VALUE 'FINANCIAL_CHANGE_AFTER_CLOSING';
