-- Pedidos de Venda — Detalhe (Auditoria 360) — índice do vínculo com
-- Documento de Saída.
--
-- Evidência real (homolog, 24/08/2026, PostgreSQL 17.10):
--   SELECT ... FROM "OrderToCashAuditFact"
--    WHERE "stockDocumentExternalId" = <id>
--   → Seq Scan, 5 linhas retornadas, ~18.177 removidas pelo filtro,
--     shared hit=3584 buffers, ~9ms POR documento — dentro do caminho do
--     detalhe do pedido (uma vez por documento de saída, e no resolver em
--     lote via IN sobre a mesma coluna).
--
-- A coluna é Int? (NULL quando o fact não referencia documento); o índice
-- B-tree simples serve tanto ao predicado de igualdade quanto ao IN do
-- resolver em lote. Sem coluna adicional: nenhuma evidência pediu composto.
--
-- CONCURRENTLY não é usado — decisão baseada no deploy REAL deste projeto:
--   • runner: `npx prisma migrate deploy` puro (scripts/deploy-server-main-
--     update.sh), sem wrapper transacional próprio;
--   • padrão consolidado: 145 migrations com CREATE INDEX no histórico,
--     ZERO com CONCURRENTLY — este seria o primeiro, sem necessidade;
--   • volume: ~18k linhas na homolog (produção na mesma ordem — a tabela é
--     repovoada por runs do O2C audit). CREATE INDEX B-tree de Int nesse
--     volume conclui em milissegundos; o lock SHARE bloqueia writes só
--     nesse instante, e quem escreve nesta tabela é o job de auditoria,
--     não usuários interativos;
--   • falha com CONCURRENTLY deixa índice INVALID + migration marcada como
--     failed (recovery manual via `migrate resolve`) — risco operacional
--     maior que o lock de milissegundos do caminho normal.
--
-- Aditivo e reversível: só cria índice, não toca dado nem estrutura.
-- IF NOT EXISTS (padrão em 41 migrations de índice do projeto): a proteção
-- real não é contra re-aplicação (o ledger _prisma_migrations já garante
-- aplicação única) e sim contra criação MANUAL antecipada — este índice foi
-- recomendado por auditoria de performance publicada, e um operador pode
-- criá-lo à mão na homolog/produção antes do deploy desta migration; sem o
-- IF NOT EXISTS esse cenário quebraria o deploy. O nome segue a convenção
-- default do Prisma para exatamente esta definição, tornando desprezível o
-- risco de colidir com um índice divergente de mesmo nome.

CREATE INDEX IF NOT EXISTS "OrderToCashAuditFact_stockDocumentExternalId_idx"
  ON "OrderToCashAuditFact" ("stockDocumentExternalId");
