/**
 * Catálogo canônico de recursos (Prompt 02) — não ligado ao runtime de auth.
 * Naming: inglês snake_case, prefixo de domínio (ver permissions-key-naming.md).
 */

import type { PermissionContractResource } from "./types.ts";

const V = (keys: readonly string[], notes?: string) =>
  ({ action: "view" as const, legacyPermissionKeys: keys, notes });
const C = (keys: readonly string[], notes?: string) =>
  ({ action: "create" as const, legacyPermissionKeys: keys, notes });
const U = (keys: readonly string[], notes?: string) =>
  ({ action: "update" as const, legacyPermissionKeys: keys, notes });
const D = (keys: readonly string[], notes?: string) =>
  ({ action: "delete" as const, legacyPermissionKeys: keys, notes });
const X = (keys: readonly string[], notes?: string) =>
  ({ action: "export" as const, legacyPermissionKeys: keys, notes });
const E = (keys: readonly string[], notes?: string) =>
  ({ action: "execute" as const, legacyPermissionKeys: keys, notes });
const A = (keys: readonly string[], notes?: string) =>
  ({ action: "approve" as const, legacyPermissionKeys: keys, notes });
const CL = (keys: readonly string[], notes?: string) =>
  ({ action: "close" as const, legacyPermissionKeys: keys, notes });
const RP = (keys: readonly string[], notes?: string) =>
  ({ action: "reprocess" as const, legacyPermissionKeys: keys, notes });
const M = (keys: readonly string[], notes?: string) =>
  ({ action: "manage" as const, legacyPermissionKeys: keys, notes });

/**
 * Recursos canônicos. Ordem: grupos → módulos sidebar → abas/detalhes/ações.
 * Ação incluída **somente** quando há capacidade real (código/API/legado).
 */
export const PERMISSION_CONTRACT_RESOURCES: readonly PermissionContractResource[] = [
  // ─── Dashboard ─────────────────────────────────────────────
  {
    resourceKey: "dashboard",
    label: "Dashboard",
    parentKey: null,
    groupId: "dashboard",
    route: "/dashboard",
    sortOrder: 10,
    actions: [V(["dashboard.view"])],
    relatedEndpoints: ["/api/dashboard"],
    sensitivity: "low",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["dashboard"],
    moduleId: "dashboard",
  },

  // ─── Engineering (grupo estrutural) ────────────────────────
  {
    resourceKey: "engineering",
    label: "Engenharia",
    parentKey: null,
    groupId: "engineering",
    route: null,
    sortOrder: 20,
    actions: [V(["products.view"], "Grupo estrutural — view composto pelos filhos")],
    relatedEndpoints: [],
    sensitivity: "low",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    notes: "Grupo accordion; sem resourceKey no seed atual.",
  },
  {
    resourceKey: "engineering.products",
    label: "Produtos",
    parentKey: "engineering",
    groupId: "engineering",
    route: "/products",
    sortOrder: 21,
    actions: [
      V(["products.view"]),
      C(["products.create"]),
      U(["products.edit"], "legado products.edit"),
      D(["products.delete"]),
      X(["products.export.engineering"]),
    ],
    relatedEndpoints: ["/api/products", "/api/products/:id", "/api/products/bulk-delete"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "products",
  },
  {
    resourceKey: "engineering.products.tab.info",
    label: "Produto — Info",
    parentKey: "engineering.products",
    groupId: "engineering",
    route: null,
    sortOrder: 211,
    actions: [V(["products.tab.info"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "engineering.products.tab.bom",
    label: "Produto — BOM",
    parentKey: "engineering.products",
    groupId: "engineering",
    route: null,
    sortOrder: 212,
    actions: [V(["products.tab.bom"])],
    relatedEndpoints: [],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "engineering.products.tab.routing",
    label: "Produto — Roteiro",
    parentKey: "engineering.products",
    groupId: "engineering",
    route: null,
    sortOrder: 213,
    actions: [V(["products.tab.routing"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "engineering.products.tab.tree",
    label: "Produto — Árvore",
    parentKey: "engineering.products",
    groupId: "engineering",
    route: null,
    sortOrder: 214,
    actions: [V(["products.tab.tree"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "engineering.products.tab.cost",
    label: "Produto — Custo",
    parentKey: "engineering.products",
    groupId: "engineering",
    route: null,
    sortOrder: 215,
    actions: [V(["products.tab.cost"])],
    relatedEndpoints: ["/api/products/:id/cost-analysis"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "engineering.products.tab.composition",
    label: "Produto — Composição",
    parentKey: "engineering.products",
    groupId: "engineering",
    route: null,
    sortOrder: 216,
    actions: [V(["products.tab.composition"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "engineering.transformation_simulator",
    label: "Simulador de Custo de Injeção",
    parentKey: "engineering",
    groupId: "engineering",
    route: "/transformation-simulator",
    sortOrder: 22,
    actions: [
      V(["products.view", "simulations.view", "costs.view"], "OR de acesso ao módulo"),
    ],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "transformation-simulator",
  },
  {
    resourceKey: "engineering.materials",
    label: "Suprimentos",
    parentKey: "engineering",
    groupId: "engineering",
    route: "/materials",
    sortOrder: 23,
    actions: [
      V(["materials.view", "costs.view"]),
      U(["materials.edit"], "legado materials.edit"),
    ],
    relatedEndpoints: ["/api/materials"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["suprimentos", "suprimentos.tab.catalogo"],
    moduleId: "materials",
  },
  {
    resourceKey: "engineering.materials.market_intelligence",
    label: "Inteligência de Mercado",
    parentKey: "engineering.materials",
    groupId: "engineering",
    route: "/materials/market-intelligence",
    sortOrder: 231,
    actions: [V(["materials.view"])],
    relatedEndpoints: ["/api/materials/market-intelligence"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["suprimentos.inteligencia_mercado"],
  },
  {
    resourceKey: "engineering.materials.market_intelligence.home",
    label: "IM — Home",
    parentKey: "engineering.materials.market_intelligence",
    groupId: "engineering",
    route: "/materials/market-intelligence",
    sortOrder: 2311,
    actions: [V(["materials.view"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["suprimentos.inteligencia_mercado.tab.home"],
  },
  {
    resourceKey: "engineering.materials.market_intelligence.material_360",
    label: "IM — Matéria-prima 360",
    parentKey: "engineering.materials.market_intelligence",
    groupId: "engineering",
    route: "/materials/market-intelligence/:materialId",
    sortOrder: 2312,
    actions: [V(["materials.view"])],
    relatedEndpoints: ["/api/materials/market-intelligence/:materialId"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: true,
    relationalResourceKeys: ["suprimentos.inteligencia_mercado.tab.materia_prima_360"],
  },
  {
    resourceKey: "engineering.materials.market_intelligence.quotes",
    label: "IM — Cotações / fornecedores",
    parentKey: "engineering.materials.market_intelligence",
    groupId: "engineering",
    route: null,
    sortOrder: 2313,
    actions: [
      V(["materials.view"]),
      U(["materials.edit"]),
      A(["materials.market_quote.approve"]),
      E(["materials.market_quote.manual_exchange"], "câmbio manual / fluxos auxiliares"),
    ],
    relatedEndpoints: [
      "/api/materials/market-intelligence/:materialId/quotes",
      "/api/materials/market-intelligence/:materialId/quotes/:quoteId/approve",
    ],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["suprimentos.inteligencia_mercado.tab.fornecedores"],
  },
  {
    resourceKey: "engineering.simulations",
    label: "Simulações",
    parentKey: "engineering",
    groupId: "engineering",
    route: "/simulations",
    sortOrder: 24,
    actions: [
      V(["simulations.view", "costs.view"]),
      C(["simulations.create"]),
    ],
    relatedEndpoints: ["/api/simulations", "/api/new-product-simulations"],
    sensitivity: "medium",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "simulations",
  },
  {
    resourceKey: "engineering.projects",
    label: "Projetos",
    parentKey: "engineering",
    groupId: "engineering",
    route: "/projects",
    sortOrder: 25,
    actions: [
      V(["projects.view"]),
      M(["projects.manage"]),
    ],
    relatedEndpoints: ["/api/projects"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "projects",
    notes: "Delete de projeto é SUPER_ADMIN inline — não modelado como delete de contrato.",
  },
  {
    resourceKey: "engineering.projects.detail",
    label: "Projeto — detalhe",
    parentKey: "engineering.projects",
    groupId: "engineering",
    route: "/projects/:id",
    sortOrder: 251,
    actions: [V(["projects.view"]), M(["projects.manage"])],
    relatedEndpoints: ["/api/projects/:id"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: true,
    relationalResourceKeys: [],
  },

  // ─── Commercial ────────────────────────────────────────────
  {
    resourceKey: "commercial",
    label: "Comercial",
    parentKey: null,
    groupId: "commercial",
    route: null,
    sortOrder: 30,
    actions: [V(["crm.view", "sales_orders.view", "proposals.view", "customers.view", "commissions.view", "pricing.view"])],
    relatedEndpoints: [],
    sensitivity: "low",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comercial"],
  },
  {
    resourceKey: "commercial.crm",
    label: "CRM Comercial",
    parentKey: "commercial",
    groupId: "commercial",
    route: "/crm-commercial",
    sortOrder: 31,
    actions: [V(["crm.view", "crm.general.view", "crm.seller.view", "crm.seller.own", "crm.seller.all"])],
    relatedEndpoints: ["/api/crm"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comercial.crm"],
    moduleId: "crm-commercial",
  },
  {
    resourceKey: "commercial.crm.general",
    label: "CRM — Gestão Geral",
    parentKey: "commercial.crm",
    groupId: "commercial",
    route: "/crm-commercial",
    sortOrder: 311,
    actions: [V(["crm.general.view"])],
    relatedEndpoints: ["/api/crm"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comercial.crm.tab.gestao_geral"],
  },
  {
    resourceKey: "commercial.crm.seller",
    label: "CRM — Gestão por Responsável",
    parentKey: "commercial.crm",
    groupId: "commercial",
    route: "/crm-commercial",
    sortOrder: 312,
    actions: [V(["crm.seller.view", "crm.seller.own", "crm.seller.all"])],
    relatedEndpoints: ["/api/crm"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comercial.crm.tab.gestao_vendedor"],
  },
  {
    resourceKey: "commercial.crm.portfolio",
    label: "CRM — Carteira de Clientes",
    parentKey: "commercial.crm",
    groupId: "commercial",
    route: "/crm-commercial",
    sortOrder: 313,
    actions: [V(["crm.view", "crm.general.view", "crm.seller.own", "crm.seller.all"])],
    relatedEndpoints: ["/api/crm"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comercial.crm.tab.carteira_clientes"],
  },
  {
    resourceKey: "commercial.crm.customer_360",
    label: "CRM — Cliente 360",
    parentKey: "commercial.crm.portfolio",
    groupId: "commercial",
    route: "/customers/:id/intelligence",
    sortOrder: 3131,
    actions: [
      V(["crm.customer_cockpit.view", "customers.commercial360.view", "customers.view"]),
    ],
    relatedEndpoints: [],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: true,
    relationalResourceKeys: ["comercial.crm.tab.cliente_360"],
  },
  {
    resourceKey: "commercial.crm.activities",
    label: "CRM — Atividades",
    parentKey: "commercial.crm",
    groupId: "commercial",
    route: null,
    sortOrder: 314,
    actions: [
      C(["crm.activities.create"]),
      U(["crm.activities.edit"]),
      U(["crm.profile.edit"], "perfil comercial"),
    ],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: true,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "commercial.crm.assign_seller",
    label: "CRM — Atribuir vendedor",
    parentKey: "commercial.crm",
    groupId: "commercial",
    route: null,
    sortOrder: 315,
    actions: [M(["crm.customers.assign_seller"])],
    relatedEndpoints: ["/api/crm/customers/:id/commercial-owner"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: true,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "commercial.customers",
    label: "Clientes",
    parentKey: "commercial",
    groupId: "commercial",
    route: "/customers",
    sortOrder: 32,
    actions: [
      V(["customers.view"]),
      C(["customers.create"]),
      U(["customers.edit"]),
    ],
    relatedEndpoints: ["/api/customers"],
    sensitivity: "medium",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "customers",
    notes: "Sem customers.delete no catálogo legado.",
  },
  {
    resourceKey: "commercial.proposals",
    label: "Propostas",
    parentKey: "commercial",
    groupId: "commercial",
    route: "/proposals",
    sortOrder: 33,
    actions: [
      V(["proposals.view"]),
      C(["proposals.create"]),
      U(["proposals.edit"]),
      D(["proposals.delete"]),
      X(["proposals.print"], "print ≈ export"),
    ],
    relatedEndpoints: ["/api/proposals"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "proposals",
  },
  {
    resourceKey: "commercial.proposals.indicators",
    label: "Propostas — Indicadores",
    parentKey: "commercial.proposals",
    groupId: "commercial",
    route: null,
    sortOrder: 331,
    actions: [V(["proposals.indicators.view"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "commercial.sales_orders",
    label: "Pedidos de venda",
    parentKey: "commercial",
    groupId: "commercial",
    route: "/sales-orders",
    sortOrder: 34,
    actions: [
      V(["sales_orders.view"]),
      X(["sales_orders.view"], "export UI hoje usa acesso ao módulo; sem chave .export dedicada"),
    ],
    relatedEndpoints: ["/api/sales-orders"],
    sensitivity: "critical",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comercial.pedidos_venda"],
    moduleId: "sales-orders",
    notes:
      "Pedido Nomus: sem create/update/delete canônico no IndusCost. Sem delete de pedido/fiscal.",
  },
  {
    resourceKey: "commercial.sales_orders.detail",
    label: "Pedido — detalhe",
    parentKey: "commercial.sales_orders",
    groupId: "commercial",
    route: "/sales-orders/:id",
    sortOrder: 341,
    actions: [V(["sales_orders.detail.view", "sales_orders.view"])],
    relatedEndpoints: ["/api/sales-orders/:id"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: true,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "commercial.sales_orders.invoice",
    label: "Pedido — NF vinculada",
    parentKey: "commercial.sales_orders",
    groupId: "commercial",
    route: null,
    sortOrder: 342,
    actions: [V(["sales_orders.invoice.view"])],
    relatedEndpoints: [],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: true,
    relationalResourceKeys: [],
    notes: "Documento fiscal: somente view — sem delete/estorno modelado aqui.",
  },
  {
    resourceKey: "commercial.pricing",
    label: "Formação de Preço",
    parentKey: "commercial",
    groupId: "commercial",
    route: "/pricing",
    sortOrder: 35,
    actions: [
      V(["pricing.view"]),
      E(["pricing.simulate"]),
      M(["pricing.generate_tables", "pricing.publish_tables"]),
    ],
    relatedEndpoints: ["/api/pricing", "/api/price-tables"],
    sensitivity: "critical",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "pricing",
    notes:
      "API hoje permite DELETE com pricing.view (gap Prompt 01). Contrato **não** inclui delete até houver chave/legado seguro.",
  },
  {
    resourceKey: "commercial.commissions",
    label: "Comissões",
    parentKey: "commercial",
    groupId: "commercial",
    route: "/commissions",
    sortOrder: 36,
    actions: [V(["commissions.view"])],
    relatedEndpoints: ["/api/commissions"],
    sensitivity: "critical",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comissoes"],
    moduleId: "commissions",
  },
  {
    resourceKey: "commercial.commissions.monthly_closing",
    label: "Comissões — Fechamento do mês",
    parentKey: "commercial.commissions",
    groupId: "commercial",
    route: "/commissions",
    sortOrder: 361,
    actions: [
      V(["commissions.view", "commissions.payments.view"]),
      CL(["commissions.payments.manage"], "aplicar fechamento / receipt-closing"),
      M(["commissions.payments.manage"], "lotes, marcar pago, cancelar lote — sem delete de ledger"),
      X(["commissions.view"], "PDF/XLSX do fechamento"),
    ],
    relatedEndpoints: [
      "/api/commissions/receipt-closing",
      "/api/commissions/payment-batches",
    ],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comissoes.tab.fechamento_mes"],
    notes: "Ledger fechado / comissão paga: sem ação delete.",
  },
  {
    resourceKey: "commercial.commissions.closings",
    label: "Comissões — Fechamentos",
    parentKey: "commercial.commissions",
    groupId: "commercial",
    route: "/commissions/fechamentos",
    sortOrder: 362,
    actions: [
      V(["commissions.view"]),
      X(["commissions.view"]),
    ],
    relatedEndpoints: ["/api/commissions/closings"],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comissoes.tab.fechamentos"],
    notes: "Relatório oficial por fechamento CLOSED — somente view/export.",
  },
  {
    resourceKey: "commercial.commissions.customer_exclusions",
    label: "Comissões — Exceções por cliente",
    parentKey: "commercial.commissions",
    groupId: "commercial",
    route: "/commissions/exclusoes-cliente",
    sortOrder: 363,
    actions: [
      V(["commissions.rules.view", "commissions.view"]),
      M(["commissions.rules.manage"]),
    ],
    relatedEndpoints: ["/api/commissions"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comissoes.tab.excecoes_cliente"],
  },
  {
    resourceKey: "commercial.commissions.reports",
    label: "Comissões — Relatórios",
    parentKey: "commercial.commissions",
    groupId: "commercial",
    route: "/commissions/relatorios",
    sortOrder: 364,
    actions: [
      V(["commissions.view", "commissions.dashboard.view", "commissions.audit.view"]),
      X(["commissions.view"]),
    ],
    relatedEndpoints: ["/api/commissions"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comissoes.tab.relatorios"],
  },
  {
    resourceKey: "commercial.commissions.reprocess",
    label: "Comissões — Reprocessar",
    parentKey: "commercial.commissions",
    groupId: "commercial",
    route: "/commissions/reprocessar",
    sortOrder: 365,
    actions: [
      V(["commissions.view"]),
      RP(["commissions.rules.manage", "commissions.payments.manage"]),
      E(["commissions.rules.manage", "commissions.payments.manage"]),
    ],
    relatedEndpoints: ["/api/commissions"],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["comissoes.tab.reprocessar"],
  },

  // ─── Finance ───────────────────────────────────────────────
  {
    resourceKey: "finance",
    label: "Financeiro",
    parentKey: null,
    groupId: "finance",
    route: "/finance",
    sortOrder: 40,
    actions: [V(["finance.view"])],
    relatedEndpoints: ["/api/finance"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["financeiro"],
    moduleId: "finance",
  },
  {
    resourceKey: "finance.cash_flow",
    label: "Fluxo de Caixa",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/cash-flow",
    sortOrder: 41,
    actions: [
      V([
        "finance.view",
        "finance.accountsReceivable.view",
        "finance.accountsPayable.view",
        "reports.view",
      ]),
    ],
    relatedEndpoints: ["/api/finance/cash-flow"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["financeiro.fluxo_caixa"],
  },
  {
    resourceKey: "finance.accounts_receivable",
    label: "Contas a Receber",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/accounts-receivable",
    sortOrder: 42,
    actions: [
      V(["finance.accountsReceivable.view", "finance.view"]),
      X(["finance.accountsReceivable.export", "finance.accountsReceivable.view"]),
      E(["settings.nomus.sync"], "sync Nomus AR — chave dedicada no UI; API OR settings.view (gap)"),
    ],
    relatedEndpoints: ["/api/finance/accounts-receivable", "/api/settings/nomus-sync"],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["financeiro.contas_receber"],
  },
  {
    resourceKey: "finance.accounts_payable",
    label: "Contas a Pagar",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/accounts-payable",
    sortOrder: 43,
    actions: [
      V(["finance.accountsPayable.view", "finance.view"]),
      X(["finance.accountsPayable.export", "finance.accountsPayable.view"]),
      M(["finance.ap_allocations.manage"]),
      E(["settings.nomus.sync"], "sync Nomus AP"),
    ],
    relatedEndpoints: ["/api/finance/accounts-payable"],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["financeiro.contas_pagar"],
  },
  {
    resourceKey: "finance.billing",
    label: "Faturamento",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/billing",
    sortOrder: 44,
    actions: [
      V(["sales_orders.view", "finance.view"]),
      E(["settings.nomus.sync"], "sync NF / billing"),
      X(["sales_orders.view"], "export lista — sem chave .export dedicada"),
    ],
    relatedEndpoints: ["/api/finance/billing"],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    notes: "NF: sem delete. Sync não é delete/estorno.",
  },
  {
    resourceKey: "finance.sales_orders",
    label: "Financeiro — Pedidos de Venda",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/sales-orders",
    sortOrder: 45,
    actions: [V(["sales_orders.view", "finance.view"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "finance.cost_centers",
    label: "Centros de Custo",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/cost-centers",
    sortOrder: 46,
    actions: [
      V(["finance.cost_centers.view", "finance.view"]),
      M(["finance.cost_centers.manage", "finance.cost_center_rules.manage"]),
    ],
    relatedEndpoints: ["/api/finance/cost-centers"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "finance.executive_report",
    label: "Relatório Presidencial",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/executive-report",
    sortOrder: 47,
    actions: [V(["reports.view", "finance.view"])],
    relatedEndpoints: ["/api/finance/executive-report"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["financeiro.relatorio_presidencial"],
  },
  {
    resourceKey: "finance.suppliers",
    label: "Fornecedores",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/suppliers",
    sortOrder: 48,
    actions: [
      V(["finance.suppliers.view", "finance.view"]),
      M(["finance.suppliers.manage"]),
    ],
    relatedEndpoints: ["/api/finance/suppliers"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "suppliers",
    notes: "DELETE supplier = SUPER_ADMIN — não é delete de contrato genérico.",
  },
  {
    resourceKey: "finance.suppliers.service_termination",
    label: "Fornecedores — Rescisão de serviço",
    parentKey: "finance.suppliers",
    groupId: "finance",
    route: null,
    sortOrder: 481,
    actions: [
      V([
        "finance.suppliers.service_termination.view",
        "suppliers.serviceTermination.view",
      ]),
      C([
        "finance.suppliers.service_termination.create",
        "suppliers.serviceTermination.create",
      ]),
      U([
        "finance.suppliers.service_termination.update",
        "suppliers.serviceTermination.update",
      ]),
      E([
        "finance.suppliers.service_termination.finalize",
        "suppliers.serviceTermination.finalize",
      ], "finalize ≈ close operacional"),
      X([
        "finance.suppliers.service_termination.export",
        "suppliers.serviceTermination.export",
      ]),
      M([
        "finance.suppliers.service_termination.cancel",
        "suppliers.serviceTermination.cancel",
      ], "cancel — não delete"),
    ],
    relatedEndpoints: ["/api/finance/suppliers"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: true,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "finance.portfolio_reconciliation",
    label: "Conciliação de Carteira",
    parentKey: "finance",
    groupId: "finance",
    route: "/finance/portfolio-reconciliation",
    sortOrder: 49,
    actions: [V(["finance.portfolioReconciliation.view"])],
    relatedEndpoints: ["/api/finance/portfolio-reconciliation"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["financeiro.conciliacao_carteira"],
    moduleId: "portfolio-reconciliation",
  },
  {
    resourceKey: "finance.portfolio_reconciliation.order_status",
    label: "Conciliação — Status Pedidos",
    parentKey: "finance.portfolio_reconciliation",
    groupId: "finance",
    route: "/finance/portfolio-reconciliation",
    sortOrder: 491,
    actions: [V(["finance.portfolioReconciliation.orderStatusPedidos.view"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["financeiro.conciliacao_carteira.tab.status_pedidos"],
  },
  {
    resourceKey: "finance.portfolio_reconciliation.order_to_cash_audit",
    label: "Conciliação — Auditoria Pedido → Caixa",
    parentKey: "finance.portfolio_reconciliation",
    groupId: "finance",
    route: "/finance/portfolio-reconciliation",
    sortOrder: 492,
    actions: [
      V(["finance.portfolioReconciliation.orderToCashAudit.view"]),
      E(["finance.portfolioReconciliation.orderToCashAudit.view"], "rebuild/jobs quando expostos"),
    ],
    relatedEndpoints: [],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["financeiro.conciliacao_carteira.tab.auditoria_pedido_caixa"],
  },
  {
    resourceKey: "finance.opex",
    label: "Custos Indiretos",
    parentKey: "finance",
    groupId: "finance",
    route: "/opex",
    sortOrder: 50,
    actions: [
      V(["opex.view", "costs.view"]),
      U(["opex.edit"]),
    ],
    relatedEndpoints: ["/api/indirect-costs"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "opex",
  },
  {
    resourceKey: "finance.taxes",
    label: "Tributos",
    parentKey: "finance",
    groupId: "finance",
    route: "/taxes",
    sortOrder: 51,
    actions: [
      V(["taxes.view"]),
      U(["taxes.edit"]),
    ],
    relatedEndpoints: ["/api/tax-rules"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "taxes",
  },
  {
    resourceKey: "finance.reports",
    label: "Relatórios",
    parentKey: "finance",
    groupId: "finance",
    route: "/reports",
    sortOrder: 52,
    actions: [V(["reports.view", "dashboard.view"])],
    relatedEndpoints: ["/api/reports/data"],
    sensitivity: "medium",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "reports",
  },

  // ─── Operations ────────────────────────────────────────────
  {
    resourceKey: "operations",
    label: "Operações",
    parentKey: null,
    groupId: "operations",
    route: null,
    sortOrder: 60,
    actions: [V(["inventory.view", "purchases.view", "machines.view", "fleet.view", "maintenance.view"])],
    relatedEndpoints: [],
    sensitivity: "low",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "operations.inventory",
    label: "Estoque / Almoxarifado",
    parentKey: "operations",
    groupId: "operations",
    route: "/inventory",
    sortOrder: 61,
    actions: [V(["inventory.view"]), M(["inventory.manage"])],
    relatedEndpoints: ["/api/inventory"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "inventory",
  },
  {
    resourceKey: "operations.inventory.items",
    label: "Estoque — Itens",
    parentKey: "operations.inventory",
    groupId: "operations",
    route: "/inventory",
    sortOrder: 611,
    actions: [V(["inventory.view"]), M(["inventory.item.manage", "inventory.manage"])],
    relatedEndpoints: [],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "operations.inventory.warehouses",
    label: "Estoque — Almoxarifados",
    parentKey: "operations.inventory",
    groupId: "operations",
    route: "/inventory",
    sortOrder: 612,
    actions: [V(["inventory.view"]), M(["inventory.warehouse.manage", "inventory.manage"])],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "operations.inventory.movements",
    label: "Estoque — Movimentações",
    parentKey: "operations.inventory",
    groupId: "operations",
    route: "/inventory",
    sortOrder: 613,
    actions: [
      V(["inventory.view"]),
      C([
        "inventory.movement.create",
        "inventory.movements.create",
        "inventory.manage",
      ]),
    ],
    relatedEndpoints: [],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "operations.inventory.counts",
    label: "Estoque — Conferência Física",
    parentKey: "operations.inventory",
    groupId: "operations",
    route: "/inventory",
    sortOrder: 614,
    actions: [
      V(["inventory.view"]),
      M(["inventory.count.manage", "inventory.manage"]),
      A(["inventory.count.approve", "inventory.manage"]),
    ],
    relatedEndpoints: [],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "operations.purchases",
    label: "Compras",
    parentKey: "operations",
    groupId: "operations",
    route: "/purchases",
    sortOrder: 62,
    actions: [
      V(["purchases.view"]),
      C(["purchases.create"]),
      U(["purchases.edit"]),
      D(["purchases.delete"], "chave no catálogo; superfície API limitada"),
    ],
    relatedEndpoints: ["/api/purchase-requests"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "purchases",
  },
  {
    resourceKey: "operations.machines",
    label: "Máquinas",
    parentKey: "operations",
    groupId: "operations",
    route: "/machines",
    sortOrder: 63,
    actions: [
      V(["machines.view", "costs.view"]),
      U(["machines.edit"]),
    ],
    relatedEndpoints: ["/api/machines"],
    sensitivity: "medium",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "machines",
  },
  {
    resourceKey: "operations.performance",
    label: "Performance",
    parentKey: "operations",
    groupId: "operations",
    route: "/operations-performance",
    sortOrder: 64,
    actions: [
      V(["operations.component-performance.view", "products.view"]),
      U(["operations.component-performance.edit"]),
    ],
    relatedEndpoints: [],
    sensitivity: "medium",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "operations-performance",
  },
  {
    resourceKey: "operations.maintenance",
    label: "Manutenção Predial",
    parentKey: "operations",
    groupId: "operations",
    route: "/maintenance",
    sortOrder: 65,
    actions: [
      V(["maintenance.view"]),
      M(["maintenance.manage"]),
    ],
    relatedEndpoints: ["/api/maintenance-requests"],
    sensitivity: "medium",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "maintenance",
  },
  {
    resourceKey: "operations.fleet",
    label: "Gestão de Frota",
    parentKey: "operations",
    groupId: "operations",
    route: "/fleet",
    sortOrder: 66,
    actions: [
      V(["fleet.view", "fleet.manage"]),
      M(["fleet.manage"]),
    ],
    relatedEndpoints: ["/api/fleet"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "fleet",
  },

  // ─── Admin ─────────────────────────────────────────────────
  {
    resourceKey: "admin",
    label: "Administração",
    parentKey: null,
    groupId: "admin",
    route: null,
    sortOrder: 70,
    actions: [V(["settings.view", "employees.view", "guide.view", "users.manage"])],
    relatedEndpoints: [],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: ["admin"],
    notes: "FE também usa chave relacional configuracoes — gap de alinhamento Prompt 01.",
  },
  {
    resourceKey: "admin.employees",
    label: "Pessoas / RH",
    parentKey: "admin",
    groupId: "admin",
    route: "/employees",
    sortOrder: 71,
    actions: [
      V(["employees.view", "costs.view"]),
      U(["employees.edit"]),
    ],
    relatedEndpoints: ["/api/employees"],
    sensitivity: "high",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "employees",
  },
  {
    resourceKey: "admin.settings",
    label: "Configurações",
    parentKey: "admin",
    groupId: "admin",
    route: "/settings",
    sortOrder: 72,
    actions: [V(["settings.view", "users.manage"])],
    relatedEndpoints: ["/api/settings"],
    sensitivity: "critical",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "settings",
    notes: "FE sidebar usa resourceKey configuracoes (fora do seed admin) — gap Prompt 01.",
  },
  {
    resourceKey: "admin.settings.security",
    label: "Configurações — Usuários e Permissões",
    parentKey: "admin.settings",
    groupId: "admin",
    route: "/settings",
    sortOrder: 721,
    actions: [
      V(["users.manage", "accessProfiles.view"]),
      M(["users.manage", "accessProfiles.manage"]),
    ],
    relatedEndpoints: ["/api/admin/users", "/api/access-profiles"],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [
      "admin.usuarios",
      "admin.permissoes",
      "admin.permissoes.action.manage",
    ],
  },
  {
    resourceKey: "admin.settings.nomus_sync",
    label: "Configurações — Sync Nomus",
    parentKey: "admin.settings",
    groupId: "admin",
    route: "/settings",
    sortOrder: 722,
    actions: [
      V(["settings.nomus.view", "settings.view"]),
      E(["settings.nomus.sync"], "runs de sync — contrato exige sync dedicado (não settings.view)"),
    ],
    relatedEndpoints: ["/api/settings/nomus-sync"],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "admin.settings.branding",
    label: "Configurações — Identidade Visual",
    parentKey: "admin.settings",
    groupId: "admin",
    route: "/settings",
    sortOrder: 723,
    actions: [V(["settings.branding.view", "settings.view"])],
    relatedEndpoints: [],
    sensitivity: "low",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "admin.settings.global_params",
    label: "Configurações — Parâmetros Globais",
    parentKey: "admin.settings",
    groupId: "admin",
    route: "/settings",
    sortOrder: 724,
    actions: [
      V(["settings.global_params.view", "settings.view"]),
      U(["settings.global_params.edit", "users.manage"]),
    ],
    relatedEndpoints: [],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "admin.settings.operational",
    label: "Configurações — Estrutura Operacional",
    parentKey: "admin.settings",
    groupId: "admin",
    route: "/settings",
    sortOrder: 725,
    actions: [V(["settings.operational.view", "settings.view"])],
    relatedEndpoints: ["/api/roles", "/api/payroll-components"],
    sensitivity: "high",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "admin.settings.price_tables",
    label: "Configurações — Tabelas de Preço",
    parentKey: "admin.settings",
    groupId: "admin",
    route: "/settings",
    sortOrder: 726,
    actions: [
      V(["settings.price_tables.view", "pricing.view", "settings.view"]),
      M(["settings.price_tables.manage", "pricing.publish_tables"]),
    ],
    relatedEndpoints: ["/api/price-tables"],
    sensitivity: "critical",
    appearsInSidebar: false,
    isTab: true,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
  },
  {
    resourceKey: "admin.guide",
    label: "Guia do Sistema",
    parentKey: "admin",
    groupId: "admin",
    route: "/guide",
    sortOrder: 73,
    actions: [V(["guide.view", "dashboard.view"])],
    relatedEndpoints: [],
    sensitivity: "low",
    appearsInSidebar: true,
    isTab: false,
    isInternalAction: false,
    isDetailScreen: false,
    relationalResourceKeys: [],
    moduleId: "guide",
  },
];

/** Recursos onde delete canônico é proibido (ledgers, fiscal, Nomus SO, pagamentos). */
export const PERMISSION_CONTRACT_FORBIDDEN_DELETE_KEYS = [
  "commercial.sales_orders",
  "commercial.sales_orders.detail",
  "commercial.sales_orders.invoice",
  "commercial.commissions.monthly_closing",
  "commercial.commissions.closings",
  "finance.billing",
  "finance.accounts_receivable",
  "finance.accounts_payable",
  "finance.cash_flow",
] as const;
