/**
 * Barrel client-safe dos contratos da Central de Tesouraria.
 * Sem Prisma e sem I/O — seguro para frontend e backend.
 *
 * Validação: parse tipado no padrão IndusCost (projeto não adota Zod).
 */

export {
  TREASURY_ACCOUNTS_PATH,
  TREASURY_AGENDA_PATH,
  TREASURY_PREDICTIVE_CRCP_BY_ACCOUNT_PATH,
  TREASURY_CAIXA_PATH,
  TREASURY_CAIXA_SCENARIOS_PATH,
  TREASURY_CASH_SUPPORT_PATH,
  TREASURY_CASH_SUPPORT_SUMMARY_PATH,
  TREASURY_CASH_SUPPORT_SUGGESTIONS_PATH,
  TREASURY_CASH_SUPPORT_TITLE_GRID_PATH,
  TREASURY_CASH_SUPPORT_AUTO_RECONCILE_PATH,
  TREASURY_CASH_SUPPORT_HISTORY_PATH,
  TREASURY_API_PREFIX,
  TREASURY_AVAILABILITY_PATH,
  TREASURY_DASHBOARD_PATH,
  TREASURY_TODAY_PATH,
  TREASURY_TODAY_OPENING_PATH,
  TREASURY_TODAY_CLOSING_PATH,
  TREASURY_DEFAULT_CURRENCY,
  TREASURY_DEFAULT_PAGE,
  TREASURY_DEFAULT_PAGE_SIZE,
  TREASURY_FIELD_LIMITS,
  TREASURY_MAX_PAGE_SIZE,
  TREASURY_MIN_PAGE_SIZE,
  TREASURY_MODULE_ID,
  TREASURY_MODULE_LABEL,
  TREASURY_COLLECTION_ACTIONS_PATH,
  TREASURY_DISPUTES_PATH,
  TREASURY_PAYABLES_PATH,
  TREASURY_PROJECTION_DEFAULT_MAX_HORIZON_DAYS,
  TREASURY_PROJECTIONS_COMPARE_PATH,
  TREASURY_PROJECTIONS_PATH,
  TREASURY_PROMISES_PATH,
  TREASURY_RECEIVABLES_PATH,
  TREASURY_SCAFFOLD_VERSION,
  TREASURY_TRANSFERS_PATH,
  TREASURY_LEDGER_ENTRIES_PATH,
  TREASURY_PAYMENT_SCHEDULE_PATH,
  TREASURY_FORECAST_VS_ACTUAL_PATH,
  TREASURY_ALERTS_PATH,
  TREASURY_AUDIT_PATH,
  TREASURY_HEALTH_PATH,
  TREASURY_RECONCILE_WORKSPACE_PATH,
  TREASURY_EXCEPTIONS_PATH,
  TREASURY_ALERT_SETTINGS_PATH,
  TREASURY_DAILY_CLOSING_PATH,
  TREASURY_DAILY_CLOSING_PREVIEW_PATH,
  TREASURY_BANK_IMPORTS_PATH,
  TREASURY_BANK_IMPORTS_OFX_PREVIEW_PATH,
  TREASURY_BANK_IMPORTS_OFX_APPLY_PATH,
  TREASURY_BANK_MOVEMENTS_PATH,
  TREASURY_RECONCILIATIONS_PATH,
  TREASURY_REPORTS_PATH,
  TREASURY_RECONCILIATION_REVERSE_CONFIRM_PHRASE,
  TREASURY_OFX_PREVIEW_TOKEN_TTL_SECONDS,
} from "./treasuryConstants.js";
export type { TreasuryFieldLimitKey } from "./treasuryConstants.js";

export {
  TREASURY_ACCOUNT_ACCESS_LEVELS,
  TREASURY_ACCOUNT_LIQUIDITIES,
  TREASURY_ACCOUNT_SORT_FIELDS,
  TREASURY_ACCOUNT_TYPES,
  TREASURY_AGENDA_SORT_FIELDS,
  TREASURY_AVAILABILITY_STATUSES,
  TREASURY_BALANCE_LAYERS,
  TREASURY_BALANCE_ORIGINS,
  TREASURY_POSITION_VALUE_ORIGINS,
  TREASURY_BALANCE_SOURCES,
  TREASURY_CLOSING_STATUSES,
  TREASURY_DAILY_ACCOUNT_ROUTINE_STATUSES,
  TREASURY_DAILY_OPENING_BALANCE_ORIGINS,
  TREASURY_DAILY_OPENING_DIFF_JUSTIFICATION_CODES,
  TREASURY_DAILY_CLOSING_ABSOLUTE_BLOCK_CODES,
  TREASURY_DAILY_CLOSING_CAVEAT_REQUIRED_CODES,
  TREASURY_DAILY_CLOSING_WARNING_CODES,
  TREASURY_CURRENCIES,
  TREASURY_COLLECTION_ACTION_TYPES,
  TREASURY_DISPUTE_STATUSES,
  TREASURY_EXCEPTION_ENTITY_KINDS,
  TREASURY_EXCEPTION_SEVERITIES,
  TREASURY_EXCEPTION_OPERATIONAL_STATUSES,
  TREASURY_EXCEPTION_SORT_FIELDS,
  TREASURY_EXCEPTION_STATUSES,
  TREASURY_EXCEPTION_TYPES,
  TREASURY_OPEN_EXCEPTION_STATUSES,
  TREASURY_LEDGER_DIRECTIONS,
  TREASURY_LEDGER_NATURES,
  TREASURY_LEDGER_SORT_FIELDS,
  TREASURY_LEDGER_STATUSES,
  TREASURY_PROJECTION_ITEM_KINDS,
  TREASURY_PROJECTION_LAYERS,
  TREASURY_PROJECTION_RISK_CODES,
  TREASURY_PROJECTION_RUN_STATUSES,
  TREASURY_PROJECTION_RECALC_EVENT_TYPES,
  TREASURY_PROJECTION_RECALC_JOB_STATUSES,
  TREASURY_PROJECTION_SCENARIOS,
  TREASURY_ACTIVE_PROMISE_STATUSES,
  TREASURY_ACTIVE_TRANSFER_STATUSES,
  TREASURY_PROMISE_STATUSES,
  TREASURY_TRANSFER_STATUSES,
  TREASURY_PAYABLE_OPERATIONAL_STATUSES,
  TREASURY_PAYABLE_PROGRAMMING_STATUSES,
  TREASURY_PAYABLE_SORT_FIELDS,
  TREASURY_RECEIVABLE_OPERATIONAL_STATUSES,
  TREASURY_RECEIVABLE_SORT_FIELDS,
  TREASURY_REPORT_KEYS,
  TREASURY_RECONCILIATION_MATCH_STATUSES,
  TREASURY_RECONCILIATION_ALLOCATION_KINDS,
  TREASURY_RECONCILIATION_ALLOCATION_POSITIVE_KINDS,
  TREASURY_RECONCILIATION_ALLOCATION_NEGATIVE_KINDS,
  TREASURY_RECONCILIATION_SUGGESTION_CONFIDENCE_BANDS,
  TREASURY_RECONCILIATION_SUGGESTION_REASON_CODES,
  TREASURY_BANK_IMPORT_BATCH_STATUSES,
  TREASURY_BANK_OFX_FORMATS,
  TREASURY_BANK_MOVEMENT_DIRECTIONS,
  TREASURY_BANK_MOVEMENT_RECONCILIATION_STATUSES,
  TREASURY_OFX_PREVIEW_ROW_STATUSES,
  TREASURY_OFX_PREVIEW_DUPLICATE_REASONS,
  TREASURY_BANK_MOVEMENT_FILTER_BUCKETS,
  TREASURY_SCHEDULE_STATUSES,
  TREASURY_SIDES,
  TREASURY_SORT_DIRECTIONS,
  TREASURY_TITLE_OPERATIONAL_PRIORITIES,
  TREASURY_TITLE_OPERATIONAL_STATUSES,
} from "./treasuryEnums.js";
export {
  DEFAULT_TREASURY_ALERT_SETTINGS,
  TREASURY_ALERT_KIND_LABELS,
  TREASURY_ALERT_KINDS,
  TREASURY_ALERT_SETTINGS_GLOBAL_ID,
} from "./treasuryAlertConfig.js";
export type {
  TreasuryAlertKind,
  TreasuryAlertSettingsFields,
} from "./treasuryAlertConfig.js";
export type {
  TreasuryAccountAccessLevel,
  TreasuryAccountLiquidity,
  TreasuryAccountSortField,
  TreasuryAccountType,
  TreasuryAgendaSortField,
  TreasuryAvailabilityStatus,
  TreasuryBalanceLayer,
  TreasuryBalanceOrigin,
  TreasuryBalanceSource,
  TreasuryPositionValueOrigin,
  TreasuryClosingStatus,
  TreasuryDailyAccountRoutineStatus,
  TreasuryDailyOpeningBalanceOrigin,
  TreasuryDailyOpeningDiffJustificationCode,
  TreasuryDailyClosingAbsoluteBlockCode,
  TreasuryDailyClosingCaveatRequiredCode,
  TreasuryDailyClosingGateCode,
  TreasuryDailyClosingWarningCode,
  TreasuryCurrency,
  TreasuryCollectionActionType,
  TreasuryDisputeStatus,
  TreasuryExceptionEntityKind,
  TreasuryExceptionOperationalStatus,
  TreasuryExceptionSeverity,
  TreasuryExceptionSortField,
  TreasuryExceptionStatus,
  TreasuryExceptionType,
  TreasuryLedgerDirection,
  TreasuryLedgerNature,
  TreasuryLedgerSortField,
  TreasuryLedgerStatus,
  TreasuryProjectionItemKind,
  TreasuryProjectionLayer,
  TreasuryProjectionRiskCode,
  TreasuryProjectionRunStatus,
  TreasuryProjectionRecalcEventType,
  TreasuryProjectionRecalcJobStatus,
  TreasuryProjectionScenario,
  TreasuryPayableOperationalStatus,
  TreasuryPayableProgrammingStatus,
  TreasuryPayableSortField,
  TreasuryPromiseStatus,
  TreasuryReceivableOperationalStatus,
  TreasuryReceivableSortField,
  TreasuryReportKey,
  TreasuryReconciliationMatchStatus,
  TreasuryReconciliationAllocationKind,
  TreasuryReconciliationSuggestionConfidenceBand,
  TreasuryReconciliationSuggestionReasonCode,
  TreasuryBankImportBatchStatus,
  TreasuryBankOfxFormat,
  TreasuryBankMovementDirection,
  TreasuryBankMovementReconciliationStatus,
  TreasuryOfxPreviewRowStatus,
  TreasuryOfxPreviewDuplicateReason,
  TreasuryBankMovementFilterBucket,
  TreasuryScheduleStatus,
  TreasurySide,
  TreasurySortDirection,
  TreasuryTitleOperationalPriority,
  TreasuryTitleOperationalStatusCode,
  TreasuryTransferStatus,
} from "./treasuryEnums.js";

export {
  TREASURY_ERROR_CODES,
  TreasuryContractError,
  isTreasuryErrorCode,
} from "./treasuryErrorCodes.js";
export type { TreasuryErrorBody, TreasuryErrorCode } from "./treasuryErrorCodes.js";

export {
  TREASURY_CIVIL_DATE_TIMEZONE,
  isTreasuryCivilDate,
  parseOptionalTreasuryCivilDate,
  parseTreasuryCivilDate,
  todayTreasuryCivilDateInSaoPaulo,
} from "./treasuryCivilDate.js";
export type { TreasuryCivilDate } from "./treasuryCivilDate.js";

export {
  formatTreasuryTimestampIso,
  isTreasuryTimestampIso,
  parseOptionalTreasuryTimestampIso,
  parseTreasuryTimestampIso,
} from "./treasuryTimestamp.js";
export type { TreasuryTimestampIso } from "./treasuryTimestamp.js";

export {
  isTreasuryMoneyString,
  normalizeTreasuryMoneyString,
  parseOptionalTreasuryMoneyString,
  parseTreasuryMoneyString,
} from "./treasuryMoneyContract.js";
export type { TreasuryMoneyString } from "./treasuryMoneyContract.js";

export {
  buildTreasuryPaginationMeta,
  parseTreasuryAuthorizedSort,
  parseTreasuryPage,
  parseTreasuryPageSize,
  parseTreasuryPagination,
  parseTreasurySortDirection,
} from "./treasuryPagination.js";
export type {
  TreasuryPaginationInput,
  TreasuryPaginationMeta,
  TreasurySortInput,
} from "./treasuryPagination.js";

export type {
  TreasuryAvailabilityResponse,
  TreasuryAccountFinancialPositionDto,
  TreasuryBalancePositionDto,
  TreasuryBalanceSnapshotDto,
  TreasuryConsolidatedFinancialPositionDto,
  TreasuryAlertItemDto,
  TreasuryDashboardCashFlowBucketDto,
  TreasuryDashboardCompositionItemDto,
  TreasuryDashboardDto,
  TreasuryDashboardExceptionItemDto,
  TreasuryDashboardFreshnessDto,
  TreasuryDashboardSourceFreshnessDto,
  TreasuryDashboardTitleCountDto,
  TreasuryFinancialPositionDto,
  TreasuryDailyCashAccountPositionDto,
  TreasuryDailyCashConsolidatedPositionDto,
  TreasuryDailyCashPendencyDto,
  TreasuryDailyCashPositionDto,
  TreasuryDailyCashTransfersDto,
  TreasuryGuidedTodayAccountDto,
  TreasuryGuidedTodayAttentionCode,
  TreasuryGuidedTodayAttentionDto,
  TreasuryGuidedTodayConsolidatedDto,
  TreasuryGuidedTodayDto,
  TreasuryGuidedTodayStepDto,
  TreasuryGuidedTodayStepId,
  TreasuryGuidedTodayStepStatus,
  TreasuryGuidedDailyOpeningAccountDto,
  TreasuryGuidedDailyOpeningSaveItemResultDto,
  TreasuryGuidedDailyOpeningSaveResultDto,
  TreasuryGuidedDailyOpeningSituation,
  TreasuryGuidedDailyOpeningWorkspaceDto,
  TreasuryGuidedDailyClosingAccountDto,
  TreasuryGuidedDailyClosingGateItemDto,
  TreasuryGuidedDailyClosingGateSummaryDto,
  TreasuryGuidedDailyClosingInvestigationActionDto,
  TreasuryGuidedDailyClosingInvestigationActionId,
  TreasuryGuidedDailyClosingSaveItemResultDto,
  TreasuryGuidedDailyClosingSaveResultDto,
  TreasuryGuidedDailyClosingSituation,
  TreasuryGuidedDailyClosingWorkspaceDto,
  TreasuryPositionValueOriginMeta,
  TreasuryDailyClosingDto,
  TreasuryDailyClosingAccountPositionDto,
  TreasuryDailyClosingReopeningDto,
  TreasuryDailyClosingGateItemDto,
  TreasuryDailyClosingPendencyItemDto,
  TreasuryDailyClosingPreviewAccountDto,
  TreasuryDailyClosingPreviewDto,
  TreasuryDailyClosingPreviewSummaryDto,
  TreasuryCollectionActionDto,
  TreasuryDisputeDto,
  TreasuryExceptionDto,
  TreasuryFinancialAccountAccessDto,
  TreasuryFinancialAccountDto,
  TreasuryLedgerEntryDto,
  TreasuryListResponse,
  TreasuryModuleId,
  TreasuryPaymentPromiseDto,
  TreasuryPaymentScheduleItemDto,
  TreasuryAgendaDayDto,
  TreasuryAgendaDto,
  TreasuryProjectionComparisonDayDto,
  TreasuryProjectionComparisonDto,
  TreasuryProjectionComparisonScenarioMetaDto,
  TreasuryProjectionCompositionItemDto,
  TreasuryProjectionCompositionResponseDto,
  TreasuryProjectionConsolidatedDayDto,
  TreasuryProjectionDayLineDto,
  TreasuryProjectionFreshnessDto,
  TreasuryProjectionPointDto,
  TreasuryProjectionRunDto,
  TreasuryProjectionSourceFreshnessDto,
  TreasuryReconciliationMatchDto,
  TreasuryReconciliationMatchMovementDto,
  TreasuryReconciliationAllocationDto,
  TreasuryTransferDto,
  TreasuryBankImportBatchDto,
  TreasuryBankMovementDto,
  TreasuryReportCompositionItemDto,
  TreasuryReportDto,
  TreasuryReportRowDto,
  TreasuryReportTotalsDto,
} from "./treasuryDto.js";

export {
  assertTreasuryKnownString,
  isTreasuryFinancialAccountDto,
  parseTreasuryAccountsListQuery,
  parseTreasuryBalancesListQuery,
  parseTreasuryCreateAccountInput,
  parseTreasuryCreateBalanceSnapshotInput,
  parseTreasuryAgendaQuery,
  parseTreasuryDashboardQuery,
  parseTreasuryGuidedDailyOpeningQuery,
  parseTreasuryGuidedDailyOpeningSaveInput,
  parseTreasuryGuidedDailyClosingQuery,
  parseTreasuryGuidedDailyClosingSaveInput,
  parseTreasuryReportKey,
  parseTreasuryReportQuery,
  parseTreasuryDailyClosingPreviewQuery,
  parseTreasuryDailyClosingCloseInput,
  parseTreasuryDailyClosingListQuery,
  parseTreasuryDailyClosingReopenInput,
  parseTreasuryBankImportOfxApplyInput,
  parseTreasuryBankImportsListQuery,
  parseTreasuryBankMovementsListQuery,
  parseTreasuryDateRangeFilter,
  parseTreasuryProjectionCalculateInput,
  parseTreasuryProjectionCompareQuery,
  parseTreasuryProjectionCompositionQuery,
  parseTreasuryProjectionGetQuery,
  parseTreasuryProjectionLatestQuery,
  parseTreasuryDeactivateAccountInput,
  parseTreasuryEnum,
  parseTreasuryBoundedString,
  parseTreasuryManualLedgerEntryInput,
  parseTreasuryCollectionActionCancelInput,
  parseTreasuryCollectionActionCreateInput,
  parseTreasuryDisputeCreateInput,
  parseTreasuryDisputeUpdateStatusInput,
  parseTreasuryPromiseCancelInput,
  parseTreasuryPromiseCreateInput,
  parseTreasuryPromiseMarkFulfilledInput,
  parseTreasuryPutAccountAccessInput,
  parseTreasuryReactivateAccountInput,
  parseTreasuryPayableHoldInput,
  parseTreasuryPayableProgramPaymentCancelInput,
  parseTreasuryPayableProgramPaymentInput,
  parseTreasuryPayableProgramPaymentUpdateInput,
  parseTreasuryPayablesListQuery,
  parseTreasuryReceivableExpectationInput,
  parseTreasuryReceivablePromiseCreateInput,
  parseTreasuryReceivablesListQuery,
  parseTreasuryExceptionAcknowledgeInput,
  parseTreasuryExceptionAssignInput,
  parseTreasuryExceptionCancelInput,
  parseTreasuryExceptionIgnoreInput,
  parseTreasuryExceptionResolveInput,
  parseTreasuryExceptionSetDueAtInput,
  parseTreasuryExceptionSetStatusInput,
  parseTreasuryExceptionUpsertInput,
  parseTreasuryExceptionsListQuery,
  parseTreasuryTransferCancelInput,
  parseTreasuryTransferCreateInput,
  parseTreasuryTransferTransitionInput,
  parseTreasuryTransfersListQuery,
  parseTreasuryUpdateAccountInput,
} from "./treasurySchemas.js";
export type {
  TreasuryAccountsListQuery,
  TreasuryBalancesListQuery,
  TreasuryCollectionActionCancelInput,
  TreasuryCollectionActionCreateInput,
  TreasuryCreateAccountInput,
  TreasuryAgendaQuery,
  TreasuryCreateBalanceSnapshotInput,
  TreasuryDashboardQuery,
  TreasuryDailyClosingPreviewQuery,
  TreasuryDailyClosingCloseInput,
  TreasuryDailyClosingListQuery,
  TreasuryDailyClosingReopenInput,
  TreasuryBankImportOfxApplyInput,
  TreasuryBankImportsListQuery,
  TreasuryBankMovementsListQuery,
  TreasuryDailyClosingCaveatInput,
  TreasuryDeactivateAccountInput,
  TreasuryProjectionCalculateInput,
  TreasuryProjectionCompareQuery,
  TreasuryProjectionCompositionQuery,
  TreasuryProjectionGetQuery,
  TreasuryProjectionLatestQuery,
  TreasuryDisputeCreateInput,
  TreasuryDisputeUpdateStatusInput,
  TreasuryExceptionAcknowledgeInput,
  TreasuryExceptionAssignInput,
  TreasuryExceptionCancelInput,
  TreasuryExceptionIgnoreInput,
  TreasuryExceptionResolveInput,
  TreasuryExceptionSetDueAtInput,
  TreasuryExceptionSetStatusInput,
  TreasuryExceptionUpsertInput,
  TreasuryExceptionsListQuery,
  TreasuryManualLedgerEntryInput,
  TreasuryPayableHoldInput,
  TreasuryPayableProgramPaymentCancelInput,
  TreasuryPayableProgramPaymentInput,
  TreasuryPayableProgramPaymentUpdateInput,
  TreasuryPayablesListQuery,
  TreasuryPromiseCancelInput,
  TreasuryPromiseCreateInput,
  TreasuryPromiseMarkFulfilledInput,
  TreasuryPutAccountAccessInput,
  TreasuryReactivateAccountInput,
  TreasuryReceivableExpectationInput,
  TreasuryReceivablePromiseCreateInput,
  TreasuryReceivablesListQuery,
  TreasuryTransferCancelInput,
  TreasuryTransferCreateInput,
  TreasuryTransferTransitionInput,
  TreasuryTransfersListQuery,
  TreasuryUpdateAccountInput,
} from "./treasurySchemas.js";

export type {
  TreasuryCustomerCollectionHistoryItem,
  TreasuryCustomerFinancialSummaryDto,
  TreasuryCustomerFinancialSummaryResponse,
  TreasuryCustomerRecentReceiptItem,
  TreasuryReceivableActionView,
  TreasuryReceivableComplementView,
  TreasuryReceivableDetailResponse,
  TreasuryReceivableListItemDto,
  TreasuryReceivablesListResponse,
  TreasuryReceivablesListSummary,
} from "./treasuryReceivableContracts.js";

export type {
  TreasuryPayableActionView,
  TreasuryPayableComplementView,
  TreasuryPayableDetailResponse,
  TreasuryPayableListItemDto,
  TreasuryPayableProgramPaymentResponse,
  TreasuryPayableProgrammingImpactDto,
  TreasuryPayableProgrammingView,
  TreasuryPayablesListResponse,
  TreasuryPayablesListSummary,
} from "./treasuryPayableContracts.js";

export {
  TREASURY_AUDIT_ACTIONS,
  TREASURY_AUDIT_ENTITY_TYPES,
  isTreasuryAuditAction,
  isTreasuryAuditEntityType,
} from "./treasuryAuditContracts.js";
export type {
  TreasuryAuditAction,
  TreasuryAuditActorContext,
  TreasuryAuditEntityType,
  TreasuryAuditEventInput,
  TreasuryAuditLogDto,
} from "./treasuryAuditContracts.js";

export type {
  OfficialCancellationView,
  OfficialCounterpartyView,
  OfficialInvoiceRefView,
  OfficialPayableView,
  OfficialReceivableView,
  OfficialSettlementView,
  OfficialStatusView,
  OfficialTitleSourcePresenceStatus,
} from "./treasuryOfficialTitleContracts.js";
